"""English product copy. Compatibility values are deliberately not translated.

Only fixed templates call text(); values interpolated into them are opaque.
Never pass user input, file names, raw logs, or command output to label().
"""
from __future__ import annotations

from datetime import datetime

LABELS = {
    "软件无法启动或崩溃": "Software won't start or crashes",
    "游戏问题": "Gaming problems", "网络问题": "Network problems",
    "电脑卡顿": "Slow computer", "蓝屏或异常重启": "Blue screen or unexpected restart",
    "其他问题": "Other problems", "系统卡顿": "Performance",
    "软件或浏览器异常": "Software or browser", "网络或Wi-Fi异常": "Network or Wi-Fi",
    "Microsoft Store 问题": "Microsoft Store", "驱动安装与更新": "Driver installation and updates",
    "声音问题": "Audio", "蓝牙问题": "Bluetooth", "打印机问题": "Printers",
    "Windows更新问题": "Windows Update", "电池或磁盘健康": "Battery or disk health",
    "综合检查": "General check", "已解决": "Resolved", "未解决": "Unresolved",
    "稍后处理": "Later", "正常": "Normal", "提醒": "Notice", "异常": "Abnormal",
    "未知": "Unknown", "不支持": "Unsupported", "权限不足": "Permission denied",
    "信息": "Information", "低": "Low", "中": "Medium", "高": "High",
    "可完整回滚": "Can restore previous settings", "仅能尽力回滚": "Best-effort recovery only",
    "不可自动回滚": "Cannot automatically undo", "无需重启": "No restart required",
    "需要重启应用": "Restart the application", "需要重启服务": "Restart the service",
    "需要重启电脑后验证": "Verify after restarting Windows",
    "无法启动": "Won't start", "闪退": "Crashes", "无响应": "Not responding",
    "安装失败": "Installation fails", "遮挡": "Cover private areas", "裁剪": "Crop",
    "无法读取": "Unable to read", "未检测": "Not checked",
    "声音": "Audio", "蓝牙": "Bluetooth", "打印机": "Printers",
    "缓存": "Cache", "已读取": "Read", "不自动清理": "Not automatically cleaned",
    "用户文件/未知": "User files / unknown", "应用文件": "Application files",
    "缓存（按目录名称推测）": "Possible cache (based on folder name)",
    "失败": "Failed", "无法验证": "Cannot verify", "完成": "Complete", "不完整": "Incomplete",
    "已完成": "Completed", "已取消": "Cancelled", "扫描": "Check",
    "有结果": "Results found", "无结果": "No results", "解析失败": "Resolution failed",
    "响应": "Responding", "无地址结果": "No addresses", "未获得结果": "No result obtained",
    "已检查": "Checked", "收到 HTTP 响应": "HTTP response received",
    "存在静态代理": "Static proxy configured", "未获得静态代理": "No static proxy found",
    "未响应（可能禁用 ICMP）": "No response (ICMP may be disabled)",
    "部分无法验证": "Partially unverified", "无匹配事件": "No matching events",
    "未获得设备": "No device information", "当前接口不支持": "Interface unsupported",
    "未检测到记录": "No records detected", "未获得记录/接口受限": "No records / interface restricted",
    "重置": "RESET",
    "代理": "Proxy",
    "网络": "Network", "软件": "Software", "空间": "Storage", "时间线": "Timeline", "监测": "Monitoring", "症状": "Symptoms",
    "symptom": "Symptoms", "network": "Network", "software": "Software", "storage": "Storage",
    "peripheral": "Devices", "timeline": "Timeline", "monitor": "Monitoring", "processes": "Running Programs",
    "cleanup": "Cache Quarantine", "restore": "Restore Previous Settings", "test_print": "Test Print",
    "修复后复检": "Post-Repair Check",
}

MESSAGES = {
    "product.cleanup_blocked": "Not Safe to Clean Automatically",
    "product.permission_denied": "Permission denied",
    "系统信息收集未能完成。你仍可返回并重试。": "System information collection could not finish. Go back and try again.",
    "repair.review": "Review One Repair",
    "repair.run": "Run This Repair",
    "repair.cancel": "Cancel — Make No Changes",
    "商店状态读取失败，不能据此判断应用缺失": "Store status could not be read. This does not prove the app is missing.",
    "商店检查没有返回完整、可验证的数据": "Store check returned incomplete or unverifiable data.",
    "按选择更新预览": "Update Preview", "创建另一份求助包": "Create Another Support Bundle",
    "只读诊断结果会加入接下来生成的求助包。请继续填写问题描述。": "Read-only findings will be included in the next support bundle. Continue by describing the problem.",
    "将自动隐藏": "Automatic Redaction",
    "截图不会进行 OCR 脱敏。请确认截图中没有账号、聊天、订单、二维码或其他私人内容。": "Screenshots are not OCR-redacted. Check for accounts, chats, orders, QR codes and other private information.",
    "预览并编辑": "Preview and Edit", "取消勾选不希望导出的系统信息；正文也可以直接修改。": "Uncheck system information you do not want to share. You can also edit the report text directly.",
    "建议优先导出 ZIP：它包含报告、已确认的截图和校验清单。": "Export a ZIP to include the report, confirmed screenshots and checksum manifest.",
    "操作进行中": "Operation Running", "请先描述你遇到的症状": "Describe the symptoms first.",
    "症状向导：": "Symptom Guide: ", "成功": "Succeeded",
    "已按加密备份恢复原 DNS 服务器配置。": "Previous DNS server settings restored from the encrypted backup.",
    "已重置当前用户代理和 PAC。": "Current user proxy and PAC reset.", "已按备份恢复原配置。": "Previous settings restored from backup.",
    "已在默认浏览器中打开官方驱动支持页面。": "Official driver support page opened in the default browser.",
    "INF 安装尚未通过签名、硬件匹配与恢复验证，当前不可执行": "INF installation has not passed signature, hardware-match and recovery validation. It is currently blocked.",
    "DNS 复查：{0}/2 个测试域名解析成功": "DNS verification: {0}/2 test domains resolved",
    "已禁用所选当前用户启动项。": "Selected current-user startup entry disabled.",
    "已把官方 HTTPS 地址交给默认浏览器": "Official HTTPS address sent to the default browser",
    "打开网页无需回滚": "Opening a page needs no rollback", "执行中": "Running", "命令完成": "Command completed",
    "已执行：{0}；验证：{1}": "Executed: {0}; verification: {1}",
    "目标状态复查通过；请确认原问题是否解决。": "Target-state verification passed. Check whether the original problem is resolved.",
    "已回滚备份：{0}": "Restored backup: {0}", "此操作不接受目标参数": "This action does not accept target parameters.",
    "只允许修复 Microsoft Store 当前用户包": "Only the current user's Microsoft Store package can be repaired.",
    "服务不在允许列表": "Service is not allowed", "网络接口名称无效": "Invalid network interface name",
    "网络接口编号无效": "Invalid network interface ID",
    "检测到静态地址、VPN、网桥或虚拟交换机，禁止自动重置 TCP/IP": "Static addresses, VPN, bridge or virtual switch detected. Automatic TCP/IP reset is blocked.",
    "Windows Update 驱动编号无效": "Invalid Windows Update driver ID", "驱动目标无效": "Invalid driver target",
    "必须选择存在的本地 INF 文件": "Select an existing local INF file.",
    "操作超时；未强制结束系统修复进程，请稍后重新检查状态": "Operation timed out. The system repair process was not forcibly terminated; check its status later.",
    "系统拒绝了操作权限": "Windows denied permission for this operation.", "当前 Windows 版本不支持此操作": "This Windows version does not support the operation.",
    "系统操作失败（退出码 {0}）：{1}": "System operation failed (exit code {0}): {1}",
    "Microsoft Store 包存在；请实际打开商店确认能否正常使用": "Microsoft Store package exists. Open Store to check whether it works.",
    "无法确认 Microsoft Store 包存在": "Could not confirm that the Microsoft Store package exists.",
    "服务正在运行": "Service is running", "服务仍未运行或状态无法读取": "Service is still stopped, or its status is unreadable",
    "Windows DPAPI 操作失败": "Windows DPAPI operation failed", "仅支持 Windows": "Windows only",
    "注册表路径不在允许列表": "Registry path is not allowed", "备份编号无效": "Invalid backup ID", "备份路径越界": "Backup path is outside the allowed directory",
    "当前用户代理已关闭": "Current-user proxy disabled", "代理配置仍然存在": "Proxy configuration is still present",
    "备份内容无效": "Invalid backup contents", "系统命令已完成。": "System command completed.",
    "命令已完成；尚不能确认原问题是否解决。": "Command completed. Resolution of the original problem is not yet confirmed.",
    "此操作不支持自动回滚": "This action cannot be automatically undone.", "厂商支持目标无效": "Invalid vendor support target",
    "只允许打开白名单中的官方 HTTPS 驱动网站": "Only allowlisted official HTTPS driver sites may be opened.",
    "系统没有接受打开浏览器的请求": "Windows did not accept the browser-open request.",
    "只读检查不是修复操作": "A read-only check is not a repair action.", "操作不在允许列表": "Action is not allowed",
    "确认已失效或对象发生变化": "Confirmation is invalid or the target changed.",
    "确认已过期，请重新查看操作内容": "Confirmation expired. Review the operation again.",
    "用户拒绝修复：{0}": "User declined repair: {0}", "用户已取消，没有执行任何修改。": "Cancelled by user. No changes were made.",
    "此操作需要管理员权限": "This action requires administrator access.",
    "操作已完成，但复查未通过。": "Operation completed, but verification failed.",
    "操作已完成，原问题是否解决尚未验证。": "Operation completed. Resolution of the original problem is unverified.",
    "用户已取消，没有执行回滚。": "Cancelled by user. Settings were not restored.",
    "备份操作类型不受支持": "Unsupported backup action type", "此操作没有自动回滚能力": "This action has no automatic rollback.",
    "无法备份接口状态，已取消续租": "Could not back up interface status. Lease renewal cancelled.",
    "无法保存原 DNS 配置，已取消修改": "Could not save previous DNS settings. Change cancelled.",
    "备份缺少有效网卡标识": "Backup lacks a valid adapter ID", "启动项路径不受支持": "Unsupported startup entry path",
    "启动项名称无效": "Invalid startup entry name", "代理对象不受支持": "Unsupported proxy target",
    "启动项已不存在": "Startup entry no longer exists", "启动项仍然存在": "Startup entry is still present",
    "高风险操作需要完成第二次确认": "High-risk actions require a second confirmation.",
    "执行未完整完成；需要复查": "Execution did not complete fully; verification needed",
    "操作已执行，复查不可用：{0}": "Action executed; verification unavailable: {0}",
    "启动项备份必须只有一个目标": "Startup backup must contain exactly one target.",
    "备份超出代理恢复范围": "Backup exceeds the proxy restore scope", "复查失败：{0}": "Verification failed: {0}",
    "没有返回详细信息": "No details returned", "提权目标参数类型无效": "Invalid elevated target parameter type",
    "管理员辅助模式仅支持 Windows": "Administrator helper mode supports Windows only.",
    "无法启动管理员辅助进程（Windows 错误 {0}）": "Cannot start administrator helper (Windows error {0})",
    "管理员操作等待超时；未强制终止系统修复进程": "Administrator operation wait timed out. The system repair process was not forcibly terminated.",
    "提权请求不能是链接": "Elevated request must not be a link", "提权请求路径越界": "Elevated request path is outside the allowed directory",
    "提权请求编号格式无效": "Invalid elevated request ID format", "用户取消了 Windows 管理员权限确认": "User cancelled Windows administrator approval",
    "管理员辅助进程没有返回结果（退出码 {0}）": "Administrator helper returned no result (exit code {0})",
    "辅助进程结果校验失败": "Helper result validation failed", "提权请求超过大小限制": "Elevated request exceeds the size limit",
    "提权请求摘要不匹配": "Elevated request digest mismatch", "提权请求已过期": "Elevated request expired",
    "提权请求编号不匹配": "Elevated request ID mismatch", "提权请求随机标识无效": "Invalid elevated request nonce",
    "当前用户操作不能通过管理员辅助进程执行": "Current-user actions cannot run through the administrator helper.",
    "提权能力令牌无效": "Invalid elevation capability token", "管理员操作失败": "Administrator operation failed",
    "请求所有者验证仅支持 Windows": "Request ownership verification supports Windows only.",
    "无法验证当前 Windows 身份": "Cannot verify current Windows identity", "无法读取当前用户 SID": "Cannot read current user SID",
    "请求必须属于当前用户；不支持用另一个管理员账户代执行": "Requests must belong to the current user. Execution under a different administrator account is unsupported.",
    "正在创建操作快照并验证目标…": "Creating an operation snapshot and validating the target…",
    "诊断未能完成：{0}": "Diagnostics could not finish: {0}",
    "请在 Windows 用户账户控制窗口中确认此单项操作…": "Approve this one action in the Windows User Account Control prompt…",
    "正在执行所选修复；不会自动重启电脑…": "Running the selected repair. Your computer will not restart automatically…",
    "缺少有效的第二次确认": "A valid second confirmation is required.",
    "网络自动修复安全条件": "Network Repair Safety Checks", "Microsoft Store 包与策略": "Microsoft Store Package and Policies",
    "Windows Update 可用驱动": "Drivers Available from Windows Update", "系统组件与常见服务修复": "System Components and Service Repairs",
    "官方厂商驱动来源": "Official Driver Sources", "检查超时": "Check timed out",
    "无法获得可靠证据，因此没有执行或推荐自动修改。": "Reliable evidence was unavailable. No automatic changes were performed or recommended.",
    "加密服务": "Cryptographic Services", "可稍后重试并把状态加入求助包。": "Try again later and include this status in your support bundle.",
    "0x80131500/安全连接错误：优先查看“Internet TLS 设置”检查，按 Windows 支持范围勾选 TLS 1.2/1.3，而不是直接重置商店。": "0x80131500 / secure connection error: check Internet TLS Settings first. Enable TLS 1.2/1.3 only where Windows supports them, instead of immediately resetting Store.",
    "点击无反应/闪退：先在 Windows 设置 → 应用 → Microsoft Store → 高级选项中选择“修复”。": "No response or crash on opening: first choose Repair under Windows Settings → Apps → Microsoft Store → Advanced options.",
    "能打开但一直加载/网络报错：先查看 DNS、代理、HTTPS 和系统日期/时区，不要直接清空应用数据。": "Opens but keeps loading or shows network errors: check DNS, proxy, HTTPS, system date and time zone first. Do not immediately clear app data.",
    "只有修复和缓存清理无效后，再到 Windows 设置手动选择“重置”；这会清除商店应用数据。": "Only if Repair and cache clearing fail, consider Reset manually in Windows Settings. Reset clears Store app data.",
    "命令完成或包已注册不代表恢复正常；请实际打开商店并加载页面后再判断。": "A completed command or registered package does not prove recovery. Open Store and load a page to check.",
    "系统不支持此接口": "Interface unsupported on this system", "检查失败（退出码 {0}）": "Check failed (exit code {0})",
    "网络栈损坏尚无可靠证据，因此不提供全局 Winsock/TCP/IP 重置。": "No reliable evidence of network-stack damage. Global Winsock/TCP/IP reset is not offered.",
    "检测到用户或电脑策略禁用 Store，请联系管理员；修复缓存或重置应用不能绕过该策略。": "A user or computer policy disables Store. Contact your administrator; cache repair or app reset cannot bypass it.",
    "按注册、策略和实际症状选择下一步；正常注册不是启动成功的证据。": "Choose next steps using registration, policies and symptoms. Normal registration does not prove Store starts.",
    "这里只列出 Windows Update 判定为适用且未安装的驱动；不从第三方驱动站下载。": "Only uninstalled drivers considered applicable by Windows Update are listed. No third-party driver sites are used.",
    "系统": "System", "按需启动的服务停止可能正常；启动服务前请确认与当前故障相关。": "Stopped on-demand services can be normal. Confirm relevance to the problem before starting one.",
    "打开 {0} 官方驱动支持页": "Open {0} Official Driver Support",
    "会把官方 HTTPS 地址交给默认浏览器；不会自动提交序列号或运行安装器。": "Opens the official HTTPS address in your default browser. Does not automatically send serial numbers or run installers.",
    "打开 {0}": "Open {0}", "打开网页无需回滚。": "Opening a page needs no rollback.",
    "HelpPack 只允许官方 HTTPS 域名；首版不抓取页面、不静默运行厂商 EXE，也不传输序列号。": "HelpPack allows only official HTTPS domains. This edition does not scrape pages, silently run vendor EXEs or transmit serial numbers.",
    "按实际症状选择单个接口；正常的自定义 DNS 无需重置。": "Choose one interface based on symptoms. Working custom DNS settings do not need resetting.",
    "高（配置）；中（修复适用性）": "High (configuration); medium (repair applicability)",
    "可选：清理商店缓存后手动重试": "Optional: Clear Store Cache, Then Retry Manually",
    "适用于商店已注册但加载异常；不会修复策略封锁、断网或缺失的安装文件。": "For a registered Store with loading problems. Does not fix policy blocks, lost connectivity or missing installation files.",
    "运行 Windows 内置 wsreset.exe": "Run Windows wsreset.exe", "缓存会重新生成。": "The cache will be rebuilt.",
    "高级：尝试恢复当前用户商店注册": "Advanced: Restore Current User Store Registration",
    "用于注册异常。未注册不代表已卸载；若系统没有可用安装包，操作将失败并保留错误信息。": "For registration problems. Unregistered does not mean uninstalled. Without an available package, the action fails and keeps the error.",
    "优先使用已安装商店的 AppxManifest.xml；未注册时按系统支持的包系列接口尝试恢复": "Prefer the installed Store's AppxManifest.xml; where unregistered, use the supported package-family recovery interface",
    "不提供自动回滚。": "Automatic rollback is unavailable.",
    "当前用户没有商店注册记录，不能断言整台电脑已卸载商店。应先由管理员只读检查其他用户的商店包是否存在，再在原用户的非管理员会话恢复注册；本次未确认机器级安装状态，因此不提供自动注册。": "No Store registration was found for this user. This does not prove Store was removed from the computer. An administrator should first check other users' packages read-only, then restore registration in the original user's non-elevated session. Machine-wide installation was not confirmed, so automatic registration is not offered.",
    "高（注册和已检查策略）；未知（实际启动）": "High (registration and checked policies); unknown (actual startup)",
    "高（Windows Update 适用性）": "High (Windows Update applicability)",
    "尚无组件损坏证据，因此不自动推荐 DISM/SFC 修复。": "No component-damage evidence yet. DISM/SFC repair is not automatically recommended.",
    "Windows Update 没有合适驱动时，可从列表中的官方页面人工选择。": "If Windows Update has no suitable driver, use the listed official pages manually.",
    "高（来源白名单）": "High (source allowlist)", "续租 DHCP：{0}": "Renew DHCP: {0}",
    "该接口可能短暂断网。": "This interface may briefly lose connectivity.", "只对接口“{0}”执行 DHCP 续租": "Renew DHCP only for interface \"{0}\"",
    "续租本身不能可靠还原。": "A lease renewal cannot be reliably undone.", "恢复 DHCP DNS：{0}": "Restore DHCP DNS: {0}",
    "会移除该接口手动配置的 DNS 服务器。": "Removes manually configured DNS servers from this interface.",
    "只重置接口“{0}”的 DNS 为 DHCP 默认值": "Reset only interface \"{0}\" DNS to DHCP defaults",
    "使用 DPAPI 加密快照恢复原 DNS。": "Restore previous DNS from a DPAPI-encrypted snapshot.", "活动接口": "Active Interfaces",
    "查询失败不代表商店被卸载。": "A failed query does not prove Store was uninstalled.", "当前用户注册": "Current User Registration",
    "用户/电脑策略": "User / Computer Policies", "包状态": "Package Status", "自动验证边界": "Automatic Verification Limits",
    "未验证商店能否实际启动或加载内容": "Actual Store startup and content loading were not verified", "驱动更新": "Driver Updates",
    "安装驱动：{0}": "Install Driver: {0}", "驱动安装可能改变设备行为、要求重启，且不能保证自动回滚。": "Driver installation may change device behavior or require a restart. Automatic rollback is not guaranteed.",
    "重新搜索相同 UpdateID，只安装这一项 Windows Update 驱动": "Search again for the same UpdateID and install only that Windows Update driver",
    "仅能通过 Windows/设备管理器尽力回退。": "Best-effort rollback through Windows or Device Manager only.",
    "适用且未安装的驱动": "Applicable Uninstalled Drivers", "每次只安装一个驱动，并在完成后重新检查设备状态。": "Install one driver at a time, then recheck device status.",
    "Windows Update 当前没有返回适用驱动。": "Windows Update returned no applicable drivers at this time.",
    "启动服务：{0}": "Start Service: {0}", "只启动该服务，不修改启动类型。": "Starts only this service without changing its startup type.",
    "启动服务 {0}": "Start service {0}", "可人工再次停止。": "You can stop it manually later.",
    "整机厂商": "Computer Manufacturer", "允许的官方来源": "Allowed Official Sources", "未命名接口": "Unnamed interface",
    "复杂/虚拟接口": "Complex / virtual interface", "普通接口": "Ordinary interface", "没有可读取的活动接口": "No readable active interfaces",
    "稍后重新检查，或在 Windows 设置中检查已安装应用。": "Check again later, or review installed apps in Windows Settings.",
    "已注册": "Registered", "未注册（机器级安装状态尚未确认）": "Unregistered (machine-wide installation not confirmed)",
    "已禁用": "Disabled", "未发现 RemoveWindowsStore 禁用项": "No RemoveWindowsStore disabling value found",
    "厂商未知": "Manufacturer unknown", "型号未知": "Model unknown", "设备可能短暂不可用": "Device may be briefly unavailable",
    "可能需要重启": "A restart may be needed", "重新启动服务：{0}": "Restart Service: {0}",
    "会暂时中断该服务正在处理的任务，未保存的任务可能失败。": "Temporarily interrupts this service's tasks; unsaved tasks may fail.",
    "只重新启动 {0}，不改启动类型": "Restart only {0}, without changing its startup type", "无法恢复被中断的任务。": "Interrupted tasks cannot be restored.",
    "短暂断网": "Brief connection loss", "域名解析可能短暂中断": "Name resolution may be briefly interrupted",
    "未能可靠读取商店状态": "Store status could not be read reliably", "不适用": "Not applicable",
    "商店连接：Internet TLS 设置": "Store Connectivity: Internet TLS Settings", "TLS 注册表值不是 DWORD": "TLS registry value is not a DWORD",
    "只读检查用户 Internet 选项、协议策略和 Schannel 显式禁用项；不修改系统安全配置，也不代替真实 TLS 握手或商店启动验证。": "Reads user Internet options, protocol policies and explicit Schannel disable settings. Does not change security configuration or replace actual TLS handshake or Store startup verification.",
    "高（已读取配置）；未知（实际连接）": "High (read configuration); unknown (actual connection)",
    "商店出现 0x80131500、一直加载或安全连接错误时，应优先检查 TLS；这不是所有打不开问题的确定原因。": "For 0x80131500, endless loading or secure connection errors, check TLS first. TLS is not a confirmed cause of every Store startup failure.",
    "不要为兼容而启用 SSL、TLS 1.0/1.1，不关闭证书校验，不修改企业策略。": "Do not enable SSL or TLS 1.0/1.1 for compatibility, disable certificate validation or change organization policies.",
    "设置勾选或注册表正常不等于连接成功；需实际打开商店并加载页面，失败时继续排查代理、时间、DNS 和 HTTPS。": "Checked options or normal registry values do not prove connectivity. Open Store and load a page. If it fails, continue checking proxy, time, DNS and HTTPS.",
    "当前用户 Internet 协议设置": "Current User Internet Protocol Settings", "系统默认，尚未确认实际协商": "System defaults; actual negotiation not verified",
    "；Schannel 客户端有显式禁用配置": "; Schannel client has explicit disable settings", "协议管理策略": "Protocol Management Policies",
    "，应用后关闭并重新打开商店。": ". After applying, close and reopen Store.",
    "检测到协议管理策略，请联系管理员，不绕过灰色或锁定的选项。": "Protocol management policy detected. Contact your administrator; do not bypass disabled or locked options.",
    "此项仅支持 Windows。": "This check supports Windows only.", "未显式配置（使用系统默认，不能判定为关闭）": "Not explicitly configured (system defaults; not evidence of being disabled)",
    "协议掩码 0x{0:X}": "Protocol mask 0x{0:X}", "用户选项已勾选": "User option selected", "用户选项未勾选": "User option not selected",
    "存在用户/电脑策略；不自动覆盖": "User/computer policy present; not automatically overridden",
    "未发现 SecureProtocols 策略值（不代表不存在其他管理限制）": "No SecureProtocols policy value found (other management limits may still exist)",
    "控制面板 → Internet 选项 → 高级 → 安全：勾选“使用 TLS 1.2”": "Control Panel → Internet Options → Advanced → Security: select Use TLS 1.2",
    "当前 Windows 不支持；不要强行添加注册表项": "Unsupported on this Windows version; do not force registry entries",
    "和“使用 TLS 1.3”（如果界面提供）": " and Use TLS 1.3 (if available)",
    "；当前 Windows 不支持 TLS 1.3，不强行开启": "; this Windows version does not support TLS 1.3; do not force it",
    "请手动检查 Internet 选项；读取失败不代表 TLS 已关闭。": "Review Internet Options manually. Read failure does not mean TLS is disabled.",
    "无法可靠读取 TLS 配置": "TLS configuration could not be read reliably",
    "无法复核执行条件，已取消本次修改": "Could not recheck prerequisites. The change was cancelled.",
    "安全检查结果为空，已取消修改": "Safety check returned no data. The change was cancelled.",
    "请以普通用户身份启动 HelpPack，再修复当前用户的商店": "Start HelpPack as a normal user before repairing that user's Store.",
    "Store 被策略禁用，已取消修改": "Store is disabled by policy. The change was cancelled.",
    "未找到 Windows 内置缓存清理程序，已取消操作": "Windows cache-reset program not found. The operation was cancelled.",
    "当前 Windows 不支持 Reset-AppxPackage，请使用应用设置": "Reset-AppxPackage is unsupported here. Use app settings instead.",
    "尚无可靠证据定位网络栈损坏，请先执行定向网络检测": "No reliable evidence of network-stack damage. Run targeted network checks first.",
    "所选接口已变化、不是物理 DHCP 接口或无法唯一定位，已取消修改": "The interface changed, is not a physical DHCP interface or cannot be uniquely identified. Change cancelled.",
    "该服务已禁用；不会修改启动类型或覆盖管理设置": "The service is disabled. Startup types and management settings will not be overridden.",
    "Windows 有待完成的重启，请先保存工作并自行重启": "Windows has a pending restart. Save your work and restart it yourself first.",
    "尚未取得组件损坏证据，请先进行管理员只读组件检测": "No component-damage evidence. Run an administrator read-only component check first.",
    "安全检查未返回可靠数据，已取消修改": "Safety check returned no reliable data. Change cancelled.",
    "当前系统没有可验证的商店注册修复入口": "No verifiable Store-registration recovery interface is available here.",
    "当前用户尚未注册 Store；缓存清理或数据重置不适用": "Store is not registered for this user; cache or data reset is not applicable.",
    "存在静态或虚拟接口，禁止自动重置网络栈": "Static or virtual interfaces detected. Automatic network-stack reset is blocked.",
    "资源占用与高占用进程（2 秒采样）": "Resource Usage and Busy Processes (2-second sample)",
    "磁盘空间与临时目录": "Disk Space and Temporary Folders", "启动项、启动文件夹和自动服务": "Startup Entries, Folders and Automatic Services",
    "登录或开机计划任务": "Logon and Boot Scheduled Tasks", "常见浏览器状态": "Common Browser Status",
    "最近的应用崩溃与 WER 事件": "Recent App Crashes and WER Events", "网络配置、DNS 与 HTTPS": "Network Configuration, DNS and HTTPS",
    "当前用户代理、PAC 与 Hosts": "Current User Proxy, PAC and Hosts", "音频、蓝牙与打印服务": "Audio, Bluetooth and Print Services",
    "PnP 设备状态": "PnP Device Status", "Windows Update 基础状态": "Windows Update Basic Status",
    "DHCP、默认网关、DNS 服务器与 Wi-Fi 适配器": "DHCP, Default Gateway, DNS Servers and Wi-Fi Adapters",
    "打印机、默认打印机与队列": "Printers, Default Printer and Queue", "最近更新记录、失败代码与日志能力": "Recent Updates, Failure Codes and Log Availability",
    "蓝屏、异常关机与硬件错误事件": "Blue Screens, Unexpected Shutdowns and Hardware Error Events",
    "电池与磁盘健康摘要": "Battery and Disk Health Overview", "{0}: {1} 个文件 / {2:.1f} MB{3}": "{0}: {1} files / {2:.1f} MiB{3}",
    "Windows 音频": "Windows Audio", "音频终结点": "Audio Endpoint Builder", "蓝牙支持": "Bluetooth Support",
    "打印后台处理": "Print Spooler", "，跳过 {0} 项": ", skipped {0} entries",
    "发现 {0} 条元数据{1}；最近时间 {2}": "Found {0} metadata records{1}; latest: {2}",
    "未发现 WER 记录": "No WER records found", "当前系统不支持": "Unsupported on this system",
    "{0}；{1}；绕过 {2}": "{0}; {1}; bypass {2}", "没有可读取的进程样本": "No readable process samples",
    "最近事件": "Recent Events", "事件日志是排查证据；崩溃模块或单条事件不能单独证明根本原因。": "Event logs are evidence. A crash module or single event alone cannot establish a root cause.",
    "没有网络接口数据": "No network interface data", "结构化网络配置": "Structured Network Configuration",
    "配置存在不等于异常；Wi-Fi 名称不写入报告，网关、DNS 和接口地址会自动脱敏。": "A configuration is not necessarily abnormal. Wi-Fi names are excluded from reports; gateway, DNS and interface addresses are automatically redacted.",
    "已安装打印机": "Installed Printers", "队列数量是当前快照；不会自动取消任何打印任务。": "Queue counts are a current snapshot. No print jobs are cancelled automatically.",
    "更新事件": "Update Events", "事件记录可包含成功和失败；事件存在不等于当前更新仍失败。": "Events may record successes and failures. Their presence does not prove updates are still failing.",
    "发布前验证没有运行 sfc /verifyonly 或 DISM /ScanHealth，避免未经确认的长时间扫描。": "Release verification did not run sfc /verifyonly or DISM /ScanHealth, avoiding long scans without confirmation.",
    "Kernel-Power 41 只表示系统未正常关机，不等同于已经确认电源故障；事件或模块名也不能单独证明根因。": "Kernel-Power 41 records an improper shutdown, not a confirmed power-supply fault. Events and module names alone cannot establish the root cause.",
    "未检测到电池": "No battery detected", "电量 {0:.0f}% / {1}": "Charge {0:.0f}% / {1}", "磁盘": "Disks",
    "SMART 或 HealthStatus 显示正常也不能保证磁盘绝对安全；USB、RAID 和部分厂商驱动可能不提供数据。": "Normal SMART or HealthStatus does not guarantee disk safety. USB, RAID and some vendor drivers may not provide data.",
    "如出现异响、读写错误或健康异常，优先备份重要数据。": "If you hear unusual noises or see read/write or health errors, prioritize backing up important data.",
    "{0}: 权限不足或不可用": "{0}: access denied or unavailable", "（达到统计上限）": " (count limit reached)",
    "无法读取（错误 {0}）": "Unable to read (error {0})", "类型 {0}": "Type {0}", "接口不可用": "Interface unavailable",
    "未设置或无法读取": "Not configured or unreadable", "检查超时，数据不足，无法判断。": "Check timed out. Insufficient data to determine status.",
    "当前权限不足，未读取到该数据。": "Current permissions do not allow reading this data.",
    "当前 Windows 版本或组件不支持此检查。": "This Windows version or component does not support the check.",
    "检查失败，不等同于发现异常。": "A failed check is not a detected fault.", "展开证据并结合发生时间判断相关性。": "Expand the evidence and compare event times to assess relevance.",
    "采样时长": "Sample Duration", "{0:.1f} 秒": "{0:.1f} seconds", "CPU 平均占用": "Average CPU Usage",
    "内存占用": "Memory Usage", "{0:.1f}%（可用 {1:.1f} GB）": "{0:.1f}% ({1:.1f} GiB available)",
    "分页使用": "Paging Usage", "采样期网络流量": "Network Traffic During Sample",
    "发送 {0:.1f} KB，接收 {1:.1f} KB": "Sent {0:.1f} KiB, received {1:.1f} KiB", "采样期磁盘活动": "Disk Activity During Sample",
    "读取 {0:.1f} KB，写入 {1:.1f} KB": "Read {0:.1f} KiB, wrote {1:.1f} KiB", "系统运行时间": "System Uptime",
    "{0:.1f} 小时": "{0:.1f} hours", "高占用进程样本": "Busy Process Samples",
    "这是短时间采样，只能反映扫描期间的状态；单个进程短暂升高不等于它就是故障原因。": "This short sample only reflects the scan period. A brief usage spike does not prove a process caused the problem.",
    "{0}：剩余 {1:.1f} GB（{2:.1f}%）": "{0}: {1:.1f} GiB free ({2:.1f}%)",
    "空间阈值用于提醒；空间偏低可能影响更新、缓存和分页，但不能单独证明是当前故障原因。": "Space thresholds are warnings. Low space may affect updates, caches and paging, but does not alone establish the current cause.",
    "注册表启动项": "Registry Startup Entries", "启动文件夹": "Startup Folders", "自动启动服务": "Automatic Services",
    "发现启动项只说明它可能随登录或开机运行，不代表它有害或导致卡顿。": "Startup entries may run at logon or boot. Their presence does not prove they are harmful or cause slowdowns.",
    "计划任务": "Scheduled Tasks", "计划任务存在不代表异常；部分系统任务不会在普通权限下完整显示。": "Scheduled tasks are not necessarily abnormal. Some system tasks are not fully visible without administrator access.",
    "{0}：{1} 个进程": "{0}: {1} processes",
    "多进程是现代浏览器的正常设计；检测到进程或锁标记不能单独证明进程残留或配置损坏。": "Modern browsers normally use multiple processes. Processes or lock markers alone do not prove stuck processes or damaged configuration.",
    "WER 记录元数据": "WER Record Metadata", "{0}：{1}，地址 {2}": "{0}: {1}, addresses {2}",
    "失败（{0}）": "Failed ({0})", "成功（HTTP {0}）": "Succeeded (HTTP {0})",
    "DNS 和 HTTPS 分别测试，任一失败都只代表本次指定目标测试失败，不等同于整个互联网不可用。": "DNS and HTTPS are tested separately. A failure applies only to that test target, not the entire internet.",
    "用户代理": "User Proxy", "WinHTTP 默认代理": "WinHTTP Default Proxy", "Hosts 非默认重定向": "Custom Hosts Redirects",
    "代理、PAC 或 Hosts 自定义记录可能完全合法；这里只提示配置存在，不判定为恶意或故障。": "Custom proxy, PAC and Hosts entries may be legitimate. This only notes their presence, not malicious behavior or a fault.",
    "设备": "Devices", "服务未运行可能与设备不可用有关，但也可能是按需启动或该硬件不存在。": "Stopped services may relate to unavailable devices, but can also be on-demand services or belong to absent hardware.",
    "设备状态或错误码是证据；驱动日期较旧本身不能证明驱动故障。": "Device states and error codes are evidence. An older driver date alone does not prove a driver fault.",
    "这里只检查基础服务和已知重启标记，不会安装更新，也没有运行 SFC 或 DISM。": "Only basic services and known restart markers are checked. No updates are installed and SFC/DISM are not run.",
    "系统时间": "System Time", "{0} 个；最近：{1}": "{0}; latest: {1}", "未发现": "Not found", "小型转储": "Minidumps",
    "电池": "Battery", "电池设计/满充容量与循环次数": "Battery Design / Full-Charge Capacity and Cycles",
    "标准 psutil 接口不提供；厂商固件或更高权限接口可用性不确定": "Not provided by standard psutil interfaces; vendor firmware or privileged interfaces may or may not support it",
    "温度": "Temperature", "当前 Windows 标准接口无法可靠覆盖本机硬件，第一版不支持": "Standard Windows interfaces cannot reliably cover this hardware; unsupported in this edition",
    "{0}：发现 {1} 个锁标记": "{0}: found {1} lock markers", "可稍后重试。": "Try again later.",
    "高（超时状态）": "High (timeout status)", "如确有需要，可由管理员人工检查。": "If necessary, an administrator can inspect this manually.",
    "高（权限状态）": "High (permission status)", "不需要为了此项检查安装未知工具。": "Do not install unknown tools just for this check.",
    "高（支持状态）": "High (support status)", "将此状态写入求助包，供技术人员继续判断。": "Include this status in your support bundle for a technician to review.",
    "高（失败状态）": "High (failure status)", "系统返回了无法结构化读取的数据；不会解析本地化文本来猜测结果。": "The system returned data that could not be read structurally. Localized text is not parsed to guess the result.",
    "当前没有发现相关证据。": "No related evidence found at this time.",
    "{0} (PID {1}) CPU {2:.1f}% / 内存 {3:.0f} MB": "{0} (PID {1}) CPU {2:.1f}% / Memory {3:.0f} MiB",
    "问题出现时可再次扫描，对比多次结果。": "Check again when the problem occurs and compare results.",
    "中（短时采样）": "Medium (short sample)", "高（容量）；中（临时目录估算）": "High (capacity); medium (temporary folder estimate)",
    "未发现可读取的条目": "No readable entries found", "未发现文件": "No files found", "未发现可读取的第三方条目": "No readable third-party entries found",
    "如需减少启动项，只选择你明确认识且不需要自动运行的用户启动项。": "To reduce startup entries, choose only familiar user entries that you do not need to start automatically.",
    "高（枚举结果）；低（与故障的因果关系）": "High (enumeration); low (causal relationship)",
    "如浏览器无法退出，可在任务管理器中确认窗口已关闭后再检查残留进程。": "If a browser will not exit, confirm its windows are closed before checking remaining processes in Task Manager.",
    "高（进程计数）；低（故障判断）": "High (process count); low (fault assessment)",
    "结合适配器、代理、DNS 和系统时间结果继续排查。": "Continue using adapter, proxy, DNS and system time findings.",
    "中（单次连接测试）": "Medium (single connection test)", "未配置": "Not configured",
    "确认这些配置是否由你、单位网络或可信软件设置。": "Check whether you, your organization or trusted software set these values.",
    "高（配置存在性）；低（是否异常）": "High (configuration presence); low (whether abnormal)",
    "在对应 Windows 设置页确认设备存在、已启用且被选为输出或目标设备。": "In Windows Settings, confirm the device is present, enabled and selected as the output or target.",
    "如更新持续失败，可记录错误代码后使用 Windows Update 设置或官方支持渠道。": "If updates keep failing, record the error code and use Windows Update Settings or official support.",
    "日志读取能力": "Log Access", "SFC 只读验证能力": "SFC Read-Only Verification Availability",
    "DISM 扫描能力": "DISM Scan Availability", "{0}: 至少 {1} 个文件 / {2:.1f} MB（达到统计上限）": "{0}: at least {1} files / {2:.1f} MiB (count limit reached)",
    "系统默认": "System default", "直连": "Direct", "指定代理": "Specified proxy", "自动代理": "Automatic proxy",
    "无代理服务器": "No proxy server", "无": "None", "未设置": "Not set", "重置当前用户代理和 PAC": "Reset Current User Proxy and PAC",
    "可能立即改变浏览器及部分应用的联网方式；单位网络或代理软件可能因此无法连接。": "May immediately change how browsers and some apps connect. Organization networks or proxy software may lose connectivity.",
    "备份并更新 HKCU Internet Settings 的 ProxyEnable、ProxyServer 和 AutoConfigURL": "Back up and update ProxyEnable, ProxyServer and AutoConfigURL in HKCU Internet Settings",
    "从 HelpPack 备份恢复这三个值及其注册表类型。": "Restore these three values and their registry types from the HelpPack backup.",
    "超时": "Timed out", "命令或模块不可用": "Command or module unavailable", "失败（退出码 {0}）": "Failed (exit code {0})",
    "高（格式状态）": "High (format status)", "未发现相关记录": "No related records found", "磁盘剩余空间": "Free Disk Space",
    "临时目录估算": "Temporary Folder Estimate",
    "系统盘空间偏低时，优先使用 Windows“存储”设置检查可清理内容。": "If system-drive space is low, review cleanup options in Windows Storage Settings first.",
    "当前未发现明显的系统盘低空间提醒。": "No clear system-drive low-space warning detected.",
    "已安装版本": "Installed Versions", "运行中的浏览器": "Running Browsers", "配置锁标记": "Profile Lock Markers",
    "清除 DNS 客户端缓存": "Clear DNS Client Cache",
    "只清除本机缓存的域名解析结果，不会更改 DNS 服务器。": "Clears cached name-resolution results on this computer without changing DNS servers.",
    "运行 Windows 内置 ipconfig /flushdns，并重新解析两个测试域名": "Run Windows ipconfig /flushdns and resolve two test domains again",
    "无需回滚；后续解析会重新写入缓存。": "No rollback needed; later lookups repopulate the cache.",
    "网络接口": "Network Interfaces", "HTTPS 连接": "HTTPS Connection", "无法读取 Hosts 文件。": "Cannot read the Hosts file.",
    "{0}：系统未提供此服务": "{0}: service not provided by this system", "{0}：权限不足": "{0}: access denied",
    "服务状态": "Service Status", "更新相关服务": "Update Services", "等待重启标记": "Pending Restart Markers",
    "{0}：无法检查": "{0}: cannot check", "命令可用（未执行）": "Command available (not run)",
    "接通电源": "Plugged in", "使用电池": "On battery", "启用": "Enabled", "未启用": "Not enabled",
    "无服务器": "No server", "返回数据格式无法识别": "Unrecognized response structure",
    "没有可读取的分区": "No readable partitions", "数据不可用": "Data unavailable",
    "未从卸载注册表识别到常见浏览器": "No common browser identified in uninstall registry entries",
    "未发现已知锁标记": "No known lock markers found", "可由管理员人工检查。": "An administrator can inspect this manually.",
    "{0}：无法读取": "{0}: unable to read", "存在": "Present", "未发现已知标记": "No known markers found",
    "可读": "Readable", "不存在或不可读": "Absent or unreadable", "命令": "Command",
    "禁用用户启动项：{0}": "Disable User Startup Entry: {0}",
    "该程序将不再随当前用户登录自动启动；不会删除程序文件。": "The program will no longer start at current-user logon. Program files are not deleted.",
    "备份后删除 HKCU\\{0} 中名为 {1} 的值": "Back up, then remove value {1} from HKCU\\{0}",
    "从 HelpPack 备份恢复原值及注册表类型。": "Restore the original value and registry type from the HelpPack backup.",
    "版本无法读取": "Version unavailable",
    "DNS 名称过长": "DNS name is too long", "网络分层定位": "Layered Network Diagnostics",
    "目标域名：{0}": "Target hostname: {0}", "网络适配器": "Network adapters", "默认网关": "Default gateway",
    "系统 DNS 与用户指定 DNS": "System and Custom DNS", "代理与直连 HTTPS 对照": "Proxy vs Direct HTTPS",
    "默认代理路径与目标服务": "Default Proxy Path and Target Service",
    "结果仅针对本次目标；请结合其他网站及故障发生时间复查。": "These findings apply only to this target. Compare other websites and the time the problem occurred.",
    "检查完成": "Check complete",
    "请输入不含账号、密码、查询参数或片段的 HTTPS 网址": "Enter an HTTPS URL without credentials, query parameters or a fragment.",
    "此检查只访问标准 HTTPS 端口 443": "This check supports standard HTTPS port 443 only.",
    "请输入合法域名，不支持带命令或 IPv6 字面量的输入": "Enter a valid hostname. Commands and literal IPv6 addresses are not supported here.",
    "DNS 响应过短": "DNS response is too short", "DNS 响应不匹配、解析失败或被截断": "DNS response mismatch, resolution error or truncation",
    "DNS 响应计数异常": "Unexpected DNS response counts",
    "指定 DNS 可解析而系统 DNS 失败，优先检查系统解析器、DNS 服务器及缓存；这不是确定原因。": "Custom DNS resolved the name, but system DNS did not. Check the system resolver, DNS server and cache first. This is not a confirmed cause.",
    "使用系统/环境静态代理路径；目标是否绕过代理：{0}。PAC/WPAD 不由 urllib 执行，不能代表浏览器全部代理行为。": "Using the system/environment static proxy path. Target bypasses proxy: {0}. urllib does not execute PAC/WPAD scripts, so this cannot represent all browser proxy behavior.",
    "直连 HTTPS": "Direct HTTPS", "默认静态代理路径 HTTPS": "Default Static Proxy HTTPS",
    "直连与默认静态代理路径结果不同，优先检查代理/绕过列表；一次差异不能证明代理就是根因。": "Direct and default proxy paths gave different results. Check the proxy and bypass list. One difference does not prove the proxy is the root cause.",
    "若解析成功但 HTTPS 失败，核对系统时间、证书、代理/防火墙和目标可用性；不要关闭证书校验。": "If DNS works but HTTPS fails, check system time, certificates, proxy/firewall settings and target availability. Do not disable certificate validation.",
    "网址或端口格式无效": "Invalid URL or port", "DNS 响应截断": "Truncated DNS response",
    "DNS 标签无效": "Invalid DNS label", "DNS 记录截断": "Truncated DNS record", "DNS 数据截断": "Truncated DNS data",
    "完成证书校验及 HTTP 响应：{0}": "Certificate validation completed; HTTP response: {0}",
    "已收到 HTTP {0}（服务拒绝/重定向不等于网络断开）": "Received HTTP {0} (a service refusal or redirect does not mean the network is disconnected)",
    "连接失败：{0}；尚未定位 DNS/代理/TLS/防火墙具体原因": "Connection failed: {0}; DNS, proxy, TLS or firewall cause has not been identified",
    "检查已取消": "Check cancelled", "适配器": "Adapters", "网关": "Gateway", "系统 DNS": "System DNS",
    "两条解析路径结果不同；CDN、区域、缓存也会产生差异，不能仅据此断言 DNS 污染。": "Resolution results differ. CDN routing, location and caching can also cause differences; this alone does not prove DNS interference.",
    "目标服务": "Target Service",
    "目标连接层有响应；登录、页面脚本、下载和具体服务功能尚未验证。": "The target responded at the connection layer. Sign-in, page scripts, downloads and service functions were not verified.",
    "连接路径失败，不能断言目标服务宕机。": "The connection path failed. This does not prove the target service is down.",
    "DNS 指针截断": "Truncated DNS pointer",
    "代理要求身份验证（HTTP 407），未验证目标服务连接；不收集代理密码。": "The proxy requires authentication (HTTP 407). Target connectivity was not verified; proxy passwords are not collected.",
    "未检测到活动接口": "No active interface detected", "没有活动接口证据；优先检查适配器连接状态": "No active interface evidence. Check adapter connectivity first.",
    "系统接口受限，继续检查其他层": "System interface restricted; continuing with other layers",
    "未获取默认路由": "No default route retrieved", "权限/接口限制；不据此判断网络故障": "Permission/interface limits; not evidence of a network fault",
    "本次目标域名解析失败": "Target hostname did not resolve in this check",
    "系统 DNS 层本次未取得解析证据，先核对该域名及系统 DNS；也可能是域名不存在，不能认定整机断网。": "System DNS returned no resolution evidence. Check the hostname and system DNS. The domain may not exist; this does not prove the whole computer is offline.",
    "指定服务器超时、拒绝或返回无法解析的响应；不改变系统设置": "The chosen server timed out, refused the query or returned an unreadable response. System settings were not changed.",
    "DNS TCP 响应截断": "Truncated DNS TCP response", "软件专项诊断": "Software Diagnostics",
    "版本与安装路径": "Version and Installation Path", "文件签名与发布者": "File Signature and Publisher",
    "进程与无响应线索": "Process and Responsiveness Clues", "相关应用事件（最近七天，有界匹配）": "Related App Events (bounded search, last 7 days)",
    "常见运行库存在性（不是健康证明）": "Common Runtime Presence (not proof of health)", "可读取的拦截记录": "Available Blocking Records",
    "记录依据是文件元数据、当前进程和可读取日志；文件签名有效不证明程序可信或运行正常。": "Findings use file metadata, current processes and available logs. A valid signature does not prove the app is trustworthy or works correctly.",
    "日志按文件名关联，可能涉及同名程序，需核对时间、路径与事件；没有日志不证明未被拦截。": "Logs are matched by file name and may refer to another app with that name. Check timestamps, paths and events. Missing logs do not prove the app was not blocked.",
    "运行库注册存在不等于文件完整或与程序架构匹配；未解析全部依赖、安装器私有日志或第三方安全软件，不能据此排除依赖/拦截问题。": "Runtime registration does not prove files are intact or match the app's architecture. Not all dependencies, private installer logs or third-party security tools are analyzed; dependency and blocking issues remain possible.",
    "专项检查完成": "Targeted check complete", "请选择本机 EXE，不读取网络共享中的程序": "Choose a local EXE. Programs on network shares are not read.",
    "请选择存在的 EXE 和支持的故障场景": "Choose an existing EXE and a supported scenario.", "已取消专项检查": "Targeted check cancelled",
    "先核对报错、签名、架构与同一时间拦截记录，不自动绕过安全软件。": "Check errors, signature, architecture and blocking records from the same time. Security software is not bypassed automatically.",
    "核对相同时间的崩溃模块与异常码，模块出现不等于它是根因。": "Compare crash modules and exception codes at the same time. A listed module is not necessarily the root cause.",
    "Responding/CPU 是瞬时线索；等待和收集复现步骤，不自动结束进程。": "Responding/CPU are momentary clues. Wait and collect reproduction steps; processes are not terminated automatically.",
    "核对安装事件与错误码、剩余空间、权限和待重启状态，不自动卸载或重新运行安装器。": "Check installation events, error codes, free space, permissions and pending restarts. Apps are not uninstalled and installers are not rerun automatically.",
    "目录扫描结束，共 {0} 个文件": "Folder scan finished: {0} files", "路径不在用户选择的目录范围内": "Path is outside the selected folder.",
    "不能操作文件链接或重解析点": "File links and reparse points cannot be modified.", "磁盘空间分析": "Disk Space Analysis",
    "用户主动选择的目录": "Folder Selected by You", "跳过链接/不可访问项目 {0} 个；取消={1}；达到扫描上限={2}。": "Skipped {0} links/inaccessible entries; cancelled={1}; scan limit reached={2}.",
    "缓存分类是名称线索，不证明可以安全删除；应用文件和用户文件不自动清理。移出后可恢复，但同盘隔离区不会释放该分区空间。": "Cache classification is a naming clue, not proof that deletion is safe. App and user files are not automatically cleaned. Quarantined files can be restored, but same-partition quarantine does NOT free space.",
    "请先选择扫描目录": "Choose a folder to scan first.", "仅支持本机普通目录，不扫描网络共享或设备命名空间": "Only ordinary local folders are supported; network shares and device namespaces are not scanned.",
    "请选择真实目录，不支持目录链接": "Choose a real folder, not a directory link.", "清理需要逐项确认": "Each cleanup action needs confirmation.",
    "只支持预览中的缓存候选；不会移出应用或用户文件": "Only previewed cache candidates can be moved. Application and user files are excluded.",
    "文件在扫描后发生变化，请重新扫描": "The file changed after scanning. Scan again.", "隔离目录不能是链接": "Quarantine must not be a directory link.",
    "恢复需要确认": "Restoring requires confirmation.", "文件已变化或原位置已有同名文件，不能覆盖": "The file changed, or the original location already contains a file. It will not be overwritten.",
    "原目录已不存在，不能自动恢复": "The original folder no longer exists; automatic restore is unavailable.",
    "不能操作目录链接或重解析点": "Directory links and reparse points cannot be modified.", "目录排行": "Largest Folders",
    "所选目录的上级是链接，不能扫描": "A parent of the selected folder is a link. Scanning is blocked.",
    "不清理 Windows 或应用安装目录": "Windows and application installation folders are not cleaned.",
    "总量 {0:.1f} GiB，剩余 {1:.1f} GiB": "Total {0:.1f} GiB, free {1:.1f} GiB", "分区 ": "Partition ",
    "已检查 {0} 项，扫描可取消": "Checked {0} entries; you can cancel the scan",
    "外设检查结束": "Device checks complete", "仅 Windows 支持原生默认端点音量读取": "Native default-endpoint volume reading supports Windows only.",
    "默认多媒体端点音量百分比": "Default Multimedia Output Volume (%)", "静音": "Muted", "外设类型无效": "Invalid device type",
    "专项检查": "Targeted Checks", "相关服务": "Related Services",
    "经典蓝牙连接标志不保证音频配置文件已连接；此原生接口不覆盖所有 BLE 设备，BLE 配对状态无法验证时需查看 Windows 设置。": "Classic Bluetooth connection flags do not prove an audio profile is connected. This native interface does not cover all BLE devices. Check Windows Settings when BLE pairing cannot be verified.",
    "音频接口不可用（HRESULT {0:X}）": "Audio interface unavailable (HRESULT {0:X})", "经典蓝牙接口不可用": "Classic Bluetooth interface unavailable",
    "蓝牙适配器/设备": "Bluetooth Adapters / Devices",
    "输出设备与默认设备由界面列出；试听只在主动点击后播放低音量两秒声音，不调整系统音量或默认设备。": "The interface lists outputs and the default device. A quiet 2-second test plays only when requested; system volume and the default device are not changed.",
    "PrinterState 的暂停位为 1；队列/脱机标志是系统快照，未检测到队列不证明实体打印成功。测试页会消耗纸张/墨粉，需选择真实打印机并单独确认。": "PrinterState uses bit 1 for paused status. Queue/offline flags are snapshots; an empty queue does not prove physical printing succeeded. Test pages may use paper/toner and require a selected printer plus separate confirmation.",
    "打印机默认/离线/暂停": "Printer Default / Offline / Paused", "已配对": "Paired", "已记住": "Remembered",
    "当前连接标志": "Current Connection Flag", "经典蓝牙配对/连接": "Classic Bluetooth Pairing / Connection",
    "音频设备状态": "Audio Device Status", "打印队列（不读取文档名或所有者）": "Print Queue (no document names or owners)",
    "不能根据 PnP 存在推断已配对/连接。": "PnP presence does not prove pairing or connection.", "默认输出静音/音量": "Default Output Mute / Volume",
    "暂停标志": "Paused Flag", "没有可读的默认端点或接口权限受限。": "No readable default endpoint, or interface access is restricted.",
    "软件安装/崩溃": "App Installation / Crashes", "系统更新/异常重启": "Updates / Unexpected Restarts",
    "驱动配置变更": "Driver Configuration Changes", "故障时间线（最近 30 天）": "Troubleshooting Timeline (last 30 days)",
    "时间先后或相邻只是线索，不直接证明更新、驱动或软件安装导致故障。": "Event order or proximity is only a clue. It does not prove an update, driver or software installation caused the problem.",
    "日志缺失/轮转/访问受限会造成时间线不完整；驱动配置事件不是所有驱动安装的完整审计。Kernel-Power 仅说明异常关机，不证明电源损坏。": "Missing, rotated or restricted logs make the timeline incomplete. Driver configuration events are not a complete driver-install audit. Kernel-Power records unexpected shutdowns, not proof of power-supply failure.",
    "时间线整理完成": "Timeline complete", "事件 {0} / {1}：{2}": "Event {0} / {1}: {2}",
    "{0} 项，有界读取并非完整历史": "{0} entries; a bounded query, not a complete history",
    "尚未取得采样，稍后再标记": "No samples yet. Try marking an incident shortly.",
    "本次已标记 50 个片段，请停止并保存": "50 incident segments marked. Stop monitoring and save them.",
    "## 间歇性故障监测\n\n仅含资源计数，不含进程/网络目标。首次速率是采样基线；null 表示该计数无法读取，不是零活动。前后片段不证明故障原因；停止时未采满后 30 秒的片段保留 complete=false 状态。\n\n```json\n": "## Intermittent Problem Monitoring\n\nResource counters only; no processes or network destinations. Initial rates are a baseline. null means unavailable, not zero activity. Before/after segments do not prove a cause. Segments stopped before collecting 30 seconds afterward keep complete=false.\n\n```json\n",
    "读取 Windows 版本": "Reading Windows version", "读取系统架构": "Reading system architecture",
    "读取处理器信息": "Reading CPU information", "读取处理器核心数": "Reading CPU core count",
    "读取内存状态": "Reading memory status", "读取磁盘空间": "Reading disk space",
    "读取显卡信息": "Reading graphics information", "检查网络接口": "Checking network interfaces",
    "检测默认网关": "Checking the default gateway", "检测 DNS 解析": "Checking DNS resolution",
    "记录当前时间": "Recording current time", "读取开机时间": "Reading boot time",
    "收集完成": "Collection complete", "未检测到默认网关": "No default gateway detected",
    "可达": "Reachable", "未响应": "No response", "{0} 总计 {1}，剩余 {2}": "{0}: total {1}, free {2}",
    "已连接": "Connected", "未连接": "Disconnected", "，速率 {0} Mbps": ", speed {0} Mbps",
    "安装路径": "Installation path", "版本": "Version", "产品": "Product", "签名状态": "Signature status",
    "发布者": "Publisher", "编号": "ID", "当前窗口响应": "Window responding", "累计 CPU 秒数": "Accumulated CPU seconds",
    "内存（字节）": "Memory (bytes)", "运行库注册项": "Runtime registration", "注册信息存在": "Registration exists",
    "版本标记": "Version marker", "事件时间": "Event time", "事件来源": "Event source", "记录内容": "Record contents",
    "日志来源": "Log source", "读取状态": "Read status", "匹配事件": "Matching events", "接口错误类别": "Interface error type",
    "名称": "Name", "显示名称": "Display name", "设备名称": "Device name", "默认打印机": "Default printer",
    "脱机标志": "Offline flag", "打印机状态码": "Printer status code", "打印机状态位": "Printer state flags",
    "队列状态": "Queue status", "总页数": "Total pages", "已打印页数": "Pages printed", "未获得值": "Value unavailable",
    "检查时间：{0}": "Checked: {0}", "症状：{0}": "Symptoms: {0}",
    "### 有证据支持的下一步（不代表确定原因）": "### Evidence-Based Next Steps (not confirmed causes)",
    "输入包含不支持的控制字符": "Input contains unsupported control characters.", "查询超时": "Query timed out",
    "系统接口查询失败": "System interface query failed", "系统接口没有返回预期结构": "The system interface returned an unexpected structure.",
    "未取得记录；不等于没有故障": "No records retrieved; this does not rule out a problem",
    "高（仅针对检查是否完成）": "High (only for whether the check completed)",
    "用户已取消扫描": "Check cancelled by user", "扫描已取消": "Check cancelled", "只读扫描完成": "Read-only checks complete",
    "可稍后重试，或将该状态连同求助包交给技术人员。": "Try again later, or share this status and your support bundle with a technician.",
    "检查状态": "Check status", "当前权限不足，未能完成此项检查。": "This check could not finish with the current permissions.",
    "检查超时，无法判断当前状态。": "The check timed out; current status could not be determined.",
    "当前系统不支持此项检查：{0}": "This check is unsupported on this system: {0}",
    "检查失败，但其他项目将继续：{0}": "This check failed, but other checks will continue: {0}",
    "可比较项目未发现变化；不代表故障已经解决。": "Comparable checks show no changes; this does not prove the issue is resolved.",
    "历史编号无效": "Invalid history ID", "历史记录损坏": "History record is damaged",
    "历史记录编号不匹配": "History record ID does not match", "处理状态无效": "Invalid problem status",
    "命令必须是非空参数数组": "Commands require a non-empty argument list.",
    "命令参数包含不允许的控制字符": "Command arguments contain prohibited control characters.",
    "PowerShell 脚本无效": "Invalid PowerShell script", "修复命令不在允许列表": "Repair command is not allowed",
    "命令不可用": "Command unavailable",
    "此 Windows 版本未纳入第一版验证范围。": "This Windows version is outside the validated scope of this edition.",
    "本机诊断第一版仅支持 Windows。": "This edition's local diagnostics support Windows only.",
    "使用 Windows 10 兼容检查路径。": "Using Windows 10-compatible checks.",
    "使用 Windows 11 兼容检查路径。": "Using Windows 11-compatible checks.",
    "具体文件：{0}\n大小：{1} 字节\n分类：{2}\n影响：缓存可能重建；运行中的程序可能受影响。不会永久删除，会移到同盘隔离区，不会释放该分区空间。\n是否只移出这一文件？": "File: {0}\nSize: {1} bytes\nCategory: {2}\nImpact: caches may be rebuilt and running apps may be affected. The file is moved to quarantine on the same partition, not permanently deleted. This does NOT free partition space.\nMove only this file?",
    "专项排查与问题记录": "Targeted Checks and Problem History",
    "检查结果、证据与下一步会显示在这里，可滚动选择复制。": "Findings, evidence and next steps appear here. Scroll, select and copy the full text.",
    "默认只读；网址/指定 DNS 检查会联网，声音与打印只由用户主动触发。": "Read-only by default. Website and custom DNS checks use the network. Audio and printing run only when you request them.",
    "本地关键词路由，不上传症状、不使用远程 AI；匹配检查不等于认定故障原因。": "Local keyword matching: symptoms are not uploaded and no remote AI is used. A matching check does not establish a cause.",
    "自行描述症状，留空则使用上面的预设": "Describe the symptoms, or leave blank to use the selected example",
    "按症状开始只读诊断": "Run Symptom Checks",
    "\n\n专项下一步：仅某个网站失败请在“网络”页填写实际网址；软件问题请在“软件”页选择对应 EXE 与场景；耳机问题请在“外设”页检查实际输出及静音/音量。向导不会假设尚未提供的目标。": "\n\nNext steps: for one failing website, enter its address on the Network tab. For app problems, select its EXE and scenario on the Software tab. For headphones, check the output device, mute and volume on the Devices tab. The guide does not assume a target you have not supplied.",
    "会向你输入的网站发送 HTTPS HEAD 请求，并向指定 DNS 发送该域名。不修改系统 DNS；不绕过证书、不跟随重定向。PAC 自动脚本不能完整模拟。": "Sends an HTTPS HEAD request to your website and queries your chosen DNS server for its hostname. Does not change system DNS, bypass certificates or follow redirects. PAC scripts cannot be fully simulated.",
    "可选 DNS 服务器 IP，由你决定；留空不发送指定 DNS 查询": "Optional DNS server IP of your choice; leave blank to skip custom DNS queries",
    "目标网址": "Website URL", "指定 DNS": "Custom DNS", "开始网络分层检查": "Run Layered Network Checks",
    "只读检查所选 EXE，不执行它。签名或依赖存在不证明程序健康；第三方拦截日志可能不可读取。": "Reads the selected EXE without running it. A signature or installed dependency does not prove the app works. Third-party blocking logs may be unavailable.",
    "刷新正在运行的程序": "Refresh Running Programs", "选择 EXE": "Choose EXE",
    "开始软件专项检查": "Run Software Checks", "选择待诊断程序（不会运行）": "Choose Program (It Will Not Be Run)",
    "程序 (*.exe)": "Programs (*.exe)",
    "只扫描主动选择的目录；跳过链接、无权访问与隔离区，最多 20 万项/120 秒。仅缓存候选可逐项移入同盘隔离区，原图/用户文件不自动删除。同盘移出不会释放该分区空间。": "Scans only your selected folder, skipping links, inaccessible folders and quarantine. Limit: 200,000 entries or 120 seconds. Individual cache candidates can be moved to quarantine on the same partition. User files are not automatically deleted. Moving files this way does NOT free partition space.",
    "选择目录": "Choose Folder", "扫描目录与分区空间": "Analyze Folder and Disk Space",
    "预览并移出选中的一个缓存文件": "Review and Quarantine One Cache File",
    "恢复当前目录最近移出的文件（重扫后可恢复）": "Restore Last Quarantined File in This Folder",
    "选择空间分析范围": "Choose Folder to Analyze",
    "默认只读；试听不会修改系统音量。测试打印需单独确认，可能消耗纸张/墨粉，队列成功不等于实体打印成功。": "Read-only by default. Audio playback does not change system volume. Test printing needs separate confirmation and may use paper or toner. A queued job does not prove physical printing succeeded.",
    "检查所选外设": "Check Selected Device Type", "刷新输出设备（标记默认）": "Refresh Audio Outputs (Default Marked)",
    "低音量试听两秒": "Play a Quiet 2-Second Test", "刷新可用打印机": "Refresh Printers",
    "确认打印一页 HelpPack 测试页": "Review One-Page Test Print",
    "读取到 {0} 个输出设备；没有设备时不能试听。": "Found {0} audio outputs. Playback requires an available output.",
    "试听已发送到所选设备；请你确认是否听见。未调整系统静音或音量。": "Test audio sent to your selected output. Please check whether you heard it. System mute and volume were not changed.",
    "历史保存在本机且自动脱敏；状态由你标记。选择两条同类诊断可比较，指标变化不证明修复因果。": "History is stored locally with automatic redaction. You assign its status. Compare two checks of the same type; metric changes do not prove a repair caused them.",
    "刷新本地历史": "Refresh History", "查看选中记录": "View Selected Record", "比较两条记录": "Compare Two Records",
    "标记当前问题处理状态": "Set Problem Status",
    "按时间整合可读取的安装、驱动配置、更新、崩溃和异常关机事件。最近 30 天、有界查询，不声称时间相邻就是原因。": "Shows available installation, driver configuration, update, crash and unexpected shutdown events from the last 30 days. Nearby events are clues, not proof of a cause.",
    "生成故障时间线": "Build Troubleshooting Timeline",
    "由你主动开启，每两秒采样资源计数，不采集私人内容。默认保留最近 10 分钟，最长两小时。故障标记保存前 60 秒和后 30 秒；提前停止保留不完整片段。退出后停止。": "Start monitoring yourself. Resource counters are sampled every 2 seconds without collecting private content. Keeps the last 10 minutes and stops after 2 hours. An incident marker keeps the preceding 60 and following 30 seconds; stopping early keeps an incomplete segment. Monitoring ends when the app exits.",
    "监测未开启": "Monitoring Off", "开启间歇性故障监测": "Start Monitoring",
    "刚才出问题了": "A Problem Just Happened", "停止监测并查看记录": "Stop and View Samples",
    "监测开启，2 秒一次，最长两小时": "Monitoring: every 2 seconds, for up to 2 hours",
    "监测已停止；应用不会在后台继续监测。": "Monitoring stopped. The app will not keep monitoring in the background.",
    "监测": "Monitoring", "后台检查中，可取消；不会阻塞界面。": "Checking in the background. You can cancel; the window remains usable.",
    "检查完成，结果与验证边界见下方；可加入报告或复制摘要。": "Check complete. See findings and verification limits below. Add them to a report or copy a summary.",
    "症状": "Symptoms", "网络": "Network", "软件": "Software", "空间": "Storage", "外设": "Devices",
    "历史": "History", "时间线": "Timeline", "取消当前检查": "Cancel Check", "复制简洁摘要": "Copy Summary",
    "加入求助报告": "Add to Report", "将检查：": "Checks to run: ",
    "这是应用文件或用户文件，不作为缓存移出。": "This is an application or user file, not an eligible cache file.",
    "确认单项清理": "Confirm One Cache Move", "恢复缓存文件": "Restore Cache File",
    "恢复本次最近移出的文件？不覆盖原位置的同名文件。": "Restore the last quarantined file? Existing files at the original location will not be overwritten.",
    "声音输出设备与默认设备": "Audio Outputs and Default Device", "请选择输出": "Select an Output",
    "先刷新并选择一个输出设备。": "Refresh the list and select an output first.",
    "此输出不支持当前试听格式，未播放。": "This output does not support the test format. No audio was played.",
    "请先等待或取消当前检查，再单独确认测试打印。": "Wait for or cancel the current check, then confirm test printing separately.",
    "打印机不可用": "Printer Unavailable", "请刷新并选择系统中存在的打印机。": "Refresh and select an installed printer.",
    "单独确认测试打印": "Confirm Test Print Separately",
    "将向“{0}”提交一页测试页，会消耗纸张/墨粉或打开虚拟打印保存窗口。是否继续？": "Send one test page to \"{0}\"? This may use paper or toner, or open a virtual printer's save dialog. Continue?",
    "提交已确认的测试页；不强制终止打印驱动": "Submitting the confirmed test page; the printer driver will not be forcibly stopped",
    "HelpPack 测试页": "HelpPack Test Page", "HelpPack 测试页 · 请核对所选打印机": "HelpPack Test Page · Check the Selected Printer",
    "测试打印记录": "Test Print Record", "选择两条": "Select Two Records",
    "请用 Ctrl 选择两条同类诊断记录。": "Hold Ctrl to select two diagnostic records of the same type.",
    "监测中 {0:.0f} 秒 · CPU {1}% · 内存 {2}% · 缓存 {3} 项 · 最近采样耗时 {4} ms（不是应用全部资源开销）": "Monitoring {0:.0f}s · CPU {1}% · Memory {2}% · {3} samples · Last sample: {4} ms (not the app's total resource usage)",
    "请先开启监测。": "Start monitoring first.",
    "已保留故障前片段，接下来还会采集后 30 秒。": "Pre-incident samples saved. Monitoring will collect the next 30 seconds too.",
    "\n\n提前停止原因：": "\n\nEarly stop reason: ", "请等待或取消当前检查。": "Wait for or cancel the current check.",
    "列出 {0} 个可读取程序，路径仅用于你选择的检查。": "Listed {0} readable programs. Paths are used only for the checks you choose.",
    "正在取消，当前有界系统查询结束后停止。": "Cancelling after the current bounded system query finishes.",
    "脱敏后的简洁摘要已复制；粘贴发送前请再检查。": "Redacted summary copied. Review it before sharing.",
    "检查未完成：{0}（权限、接口或文件可能不可用）": "Check incomplete: {0} (permissions, interfaces or files may be unavailable)",
    "监测停止：{0}": "Monitoring stopped: {0}", "未检测到输出设备": "No audio output detected",
    "未提交，已取消": "Cancelled; not submitted", "未能提交打印任务，请检查队列和权限": "Could not submit the print job. Check the queue and permissions.",
    "打印驱动未确认完成提交，请检查队列": "The printer driver did not confirm submission. Check the queue.",
    "这两条不是结构化诊断记录": "These are not structured diagnostic records.",
    "检查目标或场景不同，不能作为同一问题的前后对比": "Targets or scenarios differ; these cannot represent before and after for the same problem.",
    "## 前后对比（时间变化不证明因果）\n\n": "## Before and After (time differences do not prove causation)\n\n",
    "；已保留现有采样。": "; existing samples have been kept.",
    "## 单项清理记录\n\n用户确认的目录内目标：{0}\n\n已移入同盘隔离区，原位置的文件不再存在。重扫所选目录后也可恢复，不会覆盖同名文件；本次只移出一个文件，未永久删除，未释放该分区空间。": "## Individual Cache Move\n\nConfirmed target within the selected folder: {0}\n\nMoved to quarantine on the same partition. It is no longer at the original location. Rescan the folder to restore it; existing files will not be overwritten. Only one file was moved, nothing was permanently deleted, and partition space was NOT freed.",
    "结果已显示，但本地历史保存失败；请手动保留。": "Findings are shown, but history could not be saved. Save them manually.",
    "（默认）": " (default)", "请核对队列和实体输出，提交不等于打印成功。提交后的队列任务不会因取消检查而自动撤销。": "Check the queue and physical output. Submission does not prove printing succeeded. Cancelling diagnostics does not cancel submitted print jobs.",
    "历史记录无法读取。": "Cannot read this history record.", "处理状态保存失败。": "Could not save the problem status.",
    "\n\n优先查看有证据的提醒：": "\n\nPrioritize evidence-backed notices: ",
    "没有检测到明确异常，不代表不存在故障": "No clear abnormality detected; this does not rule out a problem",
    "用户确认的打印机": "Printer confirmed by the user", "已提交（实体结果未验证）": "Submitted (physical output not verified)",
    "## 恢复记录\n\n本次所选缓存已恢复原位置，目录内目标：": "## Restore Record\n\nSelected cache file restored to its original location. Target within the folder: ",
    "## 本地问题处理记录\n\n": "## Local Problem History\n\n", "## 症状向导\n\n": "## Symptom Guide\n\n",
    "检查证据": "Evidence",
    "<b>{0}</b><br><br>安全等级：{1}<br>目标：{2}<br>等价操作：{3}<br>需要管理员权限：{4}<br>需要联网：{5}<br>重启要求：{6}<br>预计耗时：约 {7} 秒<br>可能影响：{8}<br>副作用：{9}<br>回滚能力：{10}<br>回滚方式：{11}<br><br><b>{12}</b><br><br>是否只执行这一项操作？": "<b>{0}</b><br><br>Safety level: {1}<br>Target: {2}<br>Operation: {3}<br>Administrator access: {4}<br>Internet access: {5}<br>Restart: {6}<br>Estimated time: about {7} seconds<br>Impact: {8}<br>Side effects: {9}<br>Recovery: {10}<br>How to restore: {11}<br><br><b>{12}</b><br><br>Run only this operation?",
    "选择最接近的问题。默认扫描只运行 L0 只读检查，不会修改系统设置、结束进程或清理文件。": "Choose the closest problem. Default diagnostics are L0 read-only checks: no settings changes, process termination or file cleanup.",
    "检查结论会展示证据和可信度。修复必须逐项确认；高风险操作需要第二次确认。管理员操作只在该动作执行期间请求 UAC，应用永不自动重启电脑。": "Findings include evidence and confidence. Confirm each repair separately; high-risk actions need a second confirmation. Administrator access is requested through UAC only for the selected operation. HelpPack never restarts your computer automatically.",
    "开发预览：新增系统修复尚待隔离 Windows 环境验收。驱动更新检查会联系 Windows Update。": "Development preview: new system repairs still need testing in an isolated Windows environment. Driver update checks contact Windows Update.",
    "尚无本机诊断历史。": "No diagnostic history yet.", "返回首页": "Home", "开始只读检查": "Run Check",
    "正在执行只读检查": "Running Read-Only Checks",
    "某些事件日志或设备查询可能需要十几秒。无法获得精确进度时，进度表示已完成的检查项目比例。": "Some event-log or device queries can take several seconds. When exact progress is unavailable, the bar shows the proportion of completed checks.",
    "取消扫描": "Cancel Check", "查看证据与建议": "Findings and Recommended Actions",
    "所选项目完整内容（可滚动、选择和复制）": "Full Details (scroll, select and copy)",
    "选择上方检查项目或证据后，在这里查看完整文字。": "Select a finding or evidence above to view its full text here.",
    "查看并确认所选修复": "Review Selected Repair", "回滚最近一次修改": "Restore Previous Settings",
    "重新选择": "Choose Another Problem", "将诊断结果加入求助包": "Add Findings to Support Bundle",
    "本机诊断 · 只读检查": "Diagnostics · Read-Only Checks", "本机诊断 · 查看证据": "Diagnostics · Findings",
    "诊断未完成": "Diagnostics Incomplete", "解释：{0}": "Explanation: {0}",
    "扫描已取消，以下结果不完整。": "Check cancelled. The findings below are incomplete.",
    "L0 只读扫描完成，没有修改系统。": "L0 read-only checks completed. No system settings were changed.",
    "没有结果": "No findings", "{0}\n复查结果：{1}": "{0}\nVerification: {1}",
    "未列出额外副作用": "No additional side effects listed",
    "高风险操作必须再次确认，且可能无法自动恢复。": "High-risk actions require a second confirmation and may not be reversible.",
    "应用只会执行这里列出的这一项操作。": "Only the operation shown here will run.",
    "确认单项修复": "Confirm One Repair", "正在执行单项修复": "Running Selected Repair",
    "本机诊断 · 执行单项修复": "Diagnostics · Selected Repair", "正在准备修复…": "Preparing the repair…",
    "\n此操作需要你稍后自行重启电脑；HelpPack 不会自动重启。": "\nRestart Windows yourself later to verify this action. HelpPack will not restart it automatically.",
    "操作已完成": "Operation Completed", "修复未完成": "Repair Incomplete",
    "没有确认修复成功：{0}": "Repair success could not be confirmed: {0}",
    "确认回滚": "Confirm Restore", "将使用备份 {0} 恢复最近一次由 HelpPack 修改的配置。是否继续？": "Restore the last settings changed by HelpPack using backup {0}?",
    "回滚完成": "Settings Restored", "上次只读扫描：{0} · {1}。历史结果已脱敏保存在本机。": "Last read-only check: {0} · {1}. Redacted history is stored locally.",
    "修复正在进行，当前操作不能安全中断；完成后会显示结果。": "A repair is running and cannot safely be interrupted. Its result will appear when it finishes.",
    "正在取消；当前检查结束后不会继续后续项目…": "Cancelling. No further checks will run after the current check finishes…",
    "安全边界": "Safety Boundaries", "检查项目 / 为什么这样判断": "Finding / Evidence",
    "状态": "Status", "严重程度": "Severity", "可信度": "Confidence",
    "可选的单项修复（没有建议时不会执行任何修改）": "Optional Individual Repairs (nothing changes without a selected action)",
    "状态：{0}": "Status: {0}", "严重程度：{0}": "Severity: {0}", "可信度：{0}": "Confidence: {0}",
    "检测证据：": "Evidence:", "证据 · {0}：{1}": "Evidence · {0}: {1}", "建议：{0}": "Recommended action: {0}",
    "请选择操作": "Select an Action", "请先选择一个具体的修复建议。": "Select a specific recommended repair first.",
    "\n现在将重新进行只读检查。": "\nRead-only checks will now run again.",
    "\n现在将自动重新进行只读检查。": "\nRead-only checks will now run again automatically.",
    "修复前后变化（变化不证明因果）：\n": "Before and After (changes do not prove causation):\n",
    "\n前后对比保存失败。": "\nCould not save the comparison.", "建议操作：": "Recommended Actions:",
    "可安全修复": "Lower-Risk Repairs", "{0} {1} 项": "{0}: {1}", "无法准备修复": "Cannot Prepare Repair",
    "是": "Yes", "否": "No", "第二次确认": "Second Confirmation",
    "此操作不可可靠回滚。请输入“{0}”继续：": "This action cannot be reliably undone. Type \"{0}\" to continue:",
    "此操作可能改变网络、驱动或系统组件，并且无法保证自动恢复。HelpPack 不会自动重启电脑。确定继续吗？": "This action may change network settings, drivers or system components. Automatic recovery is not guaranteed. HelpPack never restarts your computer automatically. Continue?",
    "\n操作记录保存失败，请手动保留结果。": "\nCould not save the operation record. Save these results manually.",
    "\n失败记录未能保存。": "\nCould not save the failure record.", "回滚失败": "Restore Failed",
    "\n\n## 本次修复记录（已脱敏）\n\n": "\n\n## Repair Record (Redacted)\n\n",
    "高风险/需二次确认": "High Risk / Second Confirmation", "时间未知": "Time unavailable",
    "类型未知": "Type unavailable", "修复后复检": "Post-Repair Verification", "需要确认": "Confirmation Required",
    "与管理员权限": "and Administrator Access",
    "## 本机只读诊断结果": "## Read-Only Diagnostics", "- 扫描开始：{0}": "- Started: {0}",
    "- 扫描结束：{0}": "- Finished: {0}", "- 扫描状态：{0}": "- Check status: {0}",
    "- 安全说明：本次扫描只执行 L0 只读检查，没有修改系统。": "- Safety: this run used L0 read-only checks and made no system changes.",
    "- 通俗解释：{0}": "- Explanation: {0}", "- 建议操作：": "- Recommended Actions:",
    "> 诊断结果是基于当前证据的排查线索，不是确定的故障原因。检查失败、权限不足、不支持和未发现异常已分别记录。": "> Findings are clues based on available evidence, not confirmed causes. Failed checks, permission limits, unsupported checks and no detected abnormalities are recorded separately.",
    "- 检查 ID：{0}": "- Check ID: {0}", "- 状态：{0}": "- Status: {0}",
    "- 严重程度：{0}": "- Severity: {0}", "- 判断可信度：{0}": "- Confidence: {0}",
    "- 安全等级：{0}": "- Safety level: {0}", "- 检测时间：{0}": "- Checked: {0}",
    "- 检测证据：": "- Evidence:", "用户已取消，结果不完整": "Cancelled by user; incomplete results",
    "求助包 HelpPack": "HelpPack — English Edition",
    "求助包  HelpPack": "HelpPack",
    "开始": "Start",
    "把电脑故障整理成一份清楚的求助报告": "Make computer problems easier to explain",
    "回答几个简单问题，HelpPack 会在本机收集必要信息，并生成可检查、可编辑的诊断报告。": "Answer a few questions. HelpPack gathers relevant information locally and creates a report you can review and edit.",
    "隐私优先": "Privacy first",
    "系统信息仅在本机处理。生成报告前，你可以检查并删除任何内容。": "System information is processed on this computer. You can review and remove anything before exporting.",
    "创建求助包": "Create Support Bundle",
    "本机诊断": "Diagnostics",
    "症状向导与专项排查": "Symptom Guide and Targeted Checks",
    "例如：双击游戏后没有反应": "For example: nothing happens when I open a game",
    "发生了什么？是否有报错？能否重复出现？": "What happened? Any error messages? Can you reproduce it?",
    "例如：更新了显卡驱动、安装了新软件": "For example: updated a graphics driver or installed software",
    "例如：重启电脑、重新安装软件": "For example: restarted the computer or reinstalled the app",
    "现在还有什么没有解决？可留空，但不会自动认定已解决。": "What is still unresolved? Leaving this blank does not mark the problem as resolved.",
    "问题类型": "Problem type", "问题标题 *": "Title *", "发生了什么 *": "What happened? *",
    "问题前做过什么": "Recent changes", "已经尝试过什么": "What have you tried?",
    "仍未解决的问题": "Unresolved issues", "处理状态（自己标记）": "Status (your assessment)",
    "添加截图": "Add Screenshots", "移除选中": "Remove Selected",
    "裁剪 / 遮挡选中截图": "Crop / Cover Selected Screenshot",
    "提醒：截图内容不会自动识别或脱敏，请在导出前自行检查。": "Screenshot contents are not automatically detected or redacted. Check them before exporting.",
    "准备开始…": "Preparing…", "所选附件预览": "Selected Attachment Preview",
    "复制当前预览的简洁问题摘要": "Copy Summary of Current Preview",
    "导出 ZIP 求助包": "Export ZIP Support Bundle", "仅导出 Markdown 报告": "Export Markdown Report Only",
    "尚未导出": "Nothing exported yet", "再创建一个求助包": "Create Another Support Bundle",
    "返回": "Back", "本机诊断 · 选择问题": "Diagnostics · Select a problem",
    "诊断结果已保留": "Findings saved",
    "只读诊断结果已加入接下来生成的求助报告；仍可取消包含系统信息。": "Read-only findings will be included in the next support report. You can still exclude system information.",
    "1 / 5  描述问题": "1 / 5 · Describe the Problem", "选择截图": "Choose Screenshots",
    "图片 (*.png *.jpg *.jpeg)": "Images (*.png *.jpg *.jpeg)",
    "2 / 5  收集信息": "2 / 5 · Collect Information", "3 / 5  检查隐私": "3 / 5 · Review Privacy",
    "收集未完成": "Collection Incomplete", "4 / 5  预览": "4 / 5 · Preview",
    "5 / 5  导出": "5 / 5 · Export", "导出 Markdown 报告": "Export Markdown Report",
    "Markdown 报告已导出：\n{0}": "Markdown report exported:\n{0}",
    "ZIP 文件 (*.zip)": "ZIP Files (*.zip)",
    "ZIP 求助包已导出：\n{0}\n\n发送前建议再检查一次报告和截图。": "ZIP support bundle exported:\n{0}\n\nReview the report and screenshots once more before sharing.",
    "稍后": "Not Now", "描述问题": "Describe the Problem",
    "不必使用专业术语，按你看到的情况填写即可。": "No technical terms needed. Describe what you saw.",
    "截图（最多 5 张）": "Screenshots (up to 5)", "开始收集": "Collect Information",
    "正在收集必要信息": "Collecting Relevant Information",
    "只读取与排查有关的系统状态，不会读取文档、密码、浏览历史或剪贴板。": "Only relevant system status is read. Documents, passwords, browser history and clipboard contents are not collected.",
    "检查隐私": "Review Privacy", "HelpPack 已自动脱敏，但自动处理不能代替你的最终检查。": "HelpPack has applied automatic redaction. You must still review the final report.",
    "已自动隐藏": "Automatic Redaction",
    "Windows 用户名、用户目录路径、IP 地址、MAC 地址、邮箱，以及常见 API Key、Token 和密码字段。": "Windows usernames, home-directory paths, IP and MAC addresses, email addresses, and common API keys, tokens and password fields.",
    "截图需要你检查": "Review Your Screenshots",
    "截图未进行 OCR 脱敏。请确认截图中没有账号、聊天、订单、二维码等私密内容。": "Screenshots are not OCR-redacted. Check for accounts, chats, orders, QR codes and other private information.",
    "选择要保留的截图：": "Choose screenshots to keep:",
    "取消勾选后，该截图不会进入 ZIP，也不会出现在报告附件列表中。": "Unchecked screenshots are excluded from the ZIP and the report's attachment list.",
    "生成预览": "Generate Preview", "预览与编辑": "Preview and Edit",
    "取消勾选不希望导出的系统信息，正文也可以直接修改。": "Uncheck system information you do not want to share. You can also edit the report text directly.",
    "包含的系统信息": "Included System Information", "确认并导出": "Review Changes and Export",
    "导出求助包": "Export Support Bundle",
    "建议优先导出 ZIP，它包含报告、已确认的截图和校验清单。": "Export a ZIP to include the report, confirmed screenshots and a checksum manifest.",
    "请先选择一张截图。": "Select a screenshot first.", "还需要一点信息": "More Information Needed",
    "请填写问题标题和“发生了什么”。": "Enter a title and describe what happened.",
    "报告为空": "Empty Report", "请保留或填写报告正文后再导出。": "Keep or enter report text before exporting.",
    "正在停止监测，请稍后再次关闭窗口。": "Stopping monitoring. Try closing the window again shortly.",
    "正在取消专项检查，请等待当前查询结束后再关闭。": "Cancelling the check. Wait for the current query to finish before closing.",
    "正在收集": "Collection Running", "请等待当前信息收集完成后再关闭。": "Wait for information collection to finish before closing.",
    "正在执行操作": "Operation Running", "请等待修复完成，或取消只读诊断后再关闭。": "Wait for the repair to finish, or cancel read-only diagnostics before closing.",
    "专项排查 · 症状与证据": "Targeted Checks · Symptoms and Evidence",
    "无法添加截图": "Cannot Add Screenshot", "无法保存处理后的副本": "Cannot Save Edited Copy",
    "截图编辑未完成": "Screenshot Editing Incomplete", "导出失败": "Export Failed",
    "无法写入所选位置，请选择其他文件夹后重试。": "Cannot write to this location. Choose another folder and try again.",
    "无法创建求助包，请确认截图仍然存在并选择其他文件夹重试。": "Cannot create the bundle. Check that screenshots still exist and try another folder.",
    "截图裁剪与手动遮挡 · 原图不改变": "Crop and Cover Screenshot · Original Unchanged",
    "在图中拖动选择区域，再点击应用。遮挡使用不透明黑色；请检查所有敏感区域，导出只用处理后的 PNG 副本。": "Drag to select an area, then apply. Private areas are covered with opaque black. Review every sensitive area; export uses an edited PNG copy only.",
    "应用选区": "Apply Selection", "撤销": "Undo", "使用处理后的副本": "Use Edited Copy", "取消": "Cancel",
    "请在图片内拖动选择有效区域": "Select a valid area inside the image.", "编辑类型无效": "Invalid edit mode.",
    "图片无法读取或超过 2000 万像素编辑上限": "Cannot read the image, or it exceeds the 20-megapixel editing limit.",
    "图片格式或内容无效": "Invalid image format or contents.", "已应用；原图未修改。": "Applied. The original image is unchanged.",
    "Windows 版本": "Windows Version", "系统架构": "System Architecture",
    "逻辑核心数": "Logical CPU Cores", "总内存": "Total Memory", "当前内存使用率": "Memory Usage",
    "磁盘分区": "Disk Partitions", "显卡": "Graphics", "网络接口状态": "Network Interfaces",
    "默认网关可达性": "Default Gateway", "DNS 解析": "DNS Resolution",
    "当前时间": "Current Time", "最近开机时间": "Last Boot Time",
    "# 求助包诊断报告": "# HelpPack Support Report", "## 问题摘要": "## Problem Summary",
    "- 问题类型：{0}": "- Problem type: {0}", "- 问题标题：{0}": "- Title: {0}",
    "- 处理状态（用户标记）：{0}": "- Status (your assessment): {0}",
    "## 用户描述": "## Your Description", "### 问题出现前的操作": "### Recent Changes",
    "## 已尝试的操作": "## Actions Already Tried", "## 仍未解决的问题": "## Unresolved Issues",
    "## 系统环境": "## System Environment", "## 硬件和资源状态": "## Hardware and Resources",
    "## 网络检测结果": "## Network Checks", "## 附件列表": "## Attachments",
    "\n如需进一步排查，请结合完整报告；转发前检查隐私。": "\nUse the full report for further investigation. Review privacy before sharing.",
    "未填写": "Not provided",
    "尚未填写；诊断正常或指标改善不代表问题已经解决。": "Not provided. Normal checks or improved metrics do not prove the issue is resolved.",
    "## 值得优先检查的方向": "## Recommended Next Checks",
    "以下内容仅是排查方向，不是确定的故障结论：请先结合报错信息、问题发生时间和可复现步骤进行核对。": "These are investigation directions, not confirmed causes. Compare them with error messages, timing and steps to reproduce the problem.",
    "## 隐私处理说明": "## Privacy Notes",
    "本报告已自动尝试隐藏用户名、用户目录、IP 地址、MAC 地址、邮箱地址及常见密钥或密码字段。": "Automatic redaction attempts to hide usernames, home paths, IP and MAC addresses, emails, and common secret or password fields.",
    "截图内容未进行 OCR 脱敏，导出前应由用户自行检查。自动脱敏可能无法覆盖所有敏感信息。": "Screenshots are not OCR-redacted. Review them before exporting. Automatic redaction may miss sensitive information.",
    "未包含此类信息": "This information was excluded.",
    "HelpPack 简洁问题摘要（检查线索不是确定原因）：\n": "HelpPack Problem Summary (findings are clues, not confirmed causes):\n",
    "无附件": "No attachments",
    "最多只能添加 5 张截图，请先移除不需要的截图。": "You can add up to 5 screenshots. Remove any you do not need first.",
    "仅支持 PNG、JPG 或 JPEG 格式的截图。": "Only PNG, JPG and JPEG screenshots are supported.",
    "找不到截图文件：{0}": "Screenshot file not found: {0}",
    "系统信息收集未能完成。你可以返回并重试。": "System information collection could not finish. Go back and try again.",
}


def text(template: str, *values) -> str:
    message = MESSAGES[template]
    return message.format(*values) if values else message


def label(internal_value: str) -> str:
    """Translate an explicitly trusted internal choice, never arbitrary data."""
    if isinstance(internal_value, str) and internal_value.startswith("症状向导："):
        return "Symptom Guide: " + ", ".join(LABELS.get(v, v) for v in internal_value.removeprefix("症状向导：").split("、"))
    return LABELS.get(internal_value, internal_value)


def format_time(value: str) -> str:
    """Human-readable timestamps; persisted data keeps its original ISO format."""
    try:
        parsed = datetime.fromisoformat(value)
    except (ValueError, AttributeError):
        return value
    zone = parsed.strftime("%z")
    suffix = "UTC" + zone[:3] + ":" + zone[3:] if zone else "time zone unavailable"
    return parsed.strftime("%Y-%m-%d %H:%M:%S") + " " + suffix
