"""Bilingual fixed copy; identifiers and user values remain opaque."""
from .edition import LANGUAGE

COPY = {
    "restart_none": ("无需重启", "No Restart Required"),
    "restart_app": ("需要重启应用", "Restart the App"),
    "restart_service": ("需要重启服务", "Restart the Service"),
    "restart_system": ("需要重启电脑后验证；请自行安排", "Verify After Restarting Windows at a Time You Choose"),
    "metadata": ("预计耗时：{0} 秒\n可能联网：{1}\n重启要求：{2}\n副作用：{3}", "Estimated time: {0} seconds\nMay use network: {1}\nRestart requirement: {2}\nSide effects: {3}"),
    "extra_badge": ("需单独确认", "Individual Confirmation Required"),
    "previous_restore": ("恢复本应用之前的修改", "Restore Previous HelpPack Changes"),
    "system_time": ("系统时间（未对照外部时钟）", "System Time (Not Compared with an External Clock)"),
    "processes": ("进程平均占用样本", "Average Process Usage Samples"),
    "rechecked": ("对应检查复查：{0}", "Related Check Recheck: {0}"),
    "partial_failure": ("失败不代表没有产生任何变化；请保留记录并再次只读检查。", "Failure does not prove that no changes occurred. Keep this record and run read-only checks again."),
    "title": ("一键修复 · 基于证据的计划", "One-Click Repair · Evidence-Based Plan"),
    "review": ("查看修复计划", "Review Repair Plan"),
    "execute": ("确认并执行所选项目", "Confirm and Run Selected Actions"),
    "cancel": ("停止调度后续动作", "Stop Scheduling Further Actions"),
    "restore": ("恢复本次修改", "Restore This Plan's Changes"),
    "report": ("将处理记录加入求助报告", "Add Repair Record to Report"),
    "none": ("没有有证据支持的适用动作。正常配置不会被清除；请查看建议或使用专项排查。", "No evidence-supported actions apply. Normal settings will not be cleared. Review the recommendations or use targeted checks."),
    "intro": ("仅执行勾选项目。可能中断网络、程序或服务的项目需再单独确认。不自动重启。", "Only checked actions will run. Actions that may interrupt networks, apps or services require individual extra confirmation. Windows will never restart automatically."),
    "details": ("证据、影响与命令细节（可展开）", "Evidence, Impact and Command Details (expandable)"),
    "item": ("动作：{0}\n目标：{1}\n依据：{2}\n预期效果 / 影响：{3}\n管理员：{4}；额外确认：{5}\n恢复能力：{6}\n操作预览：{7}", "Action: {0}\nTarget: {1}\nEvidence: {2}\nExpected effect / impact: {3}\nAdministrator: {4}; extra confirmation: {5}\nRecovery: {6}\nOperation preview: {7}"),
    "extra": ("这项动作必须单独确认：{0}\n{1}\n可能中断当前任务，无法承诺恢复所有影响。继续吗？", "Confirm this action separately: {0}\n{1}\nCurrent tasks may be interrupted. Not all effects can be undone. Continue?"),
    "running": ("{0}/{1}：{2}", "{0}/{1}: {2}"),
    "before_after": ("修改前：{0}\n复查后：{1}", "Before: {0}\nAfter: {1}"),
    "improved": ("操作成功且检测改善", "Operation Succeeded and Check Improved"),
    "unchanged": ("操作成功但问题仍存在", "Operation Succeeded but Problem Remains"),
    "failed": ("操作失败", "Operation Failed"),
    "restart": ("尚待重启后验证", "Awaiting Verification After Restart"),
    "unknown": ("无法判断", "Unable to Determine"),
    "skipped": ("未执行：取消、依赖失败或不再适用", "Not Run: Cancelled, Dependency Failed or No Longer Applicable"),
    "expired": ("计划已过期、已使用或被修改，请重新诊断并查看计划。", "The plan expired, was already used or changed. Run diagnostics and review a new plan."),
    "busy": ("另一个修复计划正在执行。", "Another repair plan is running."),
    "conflict": ("当前状态已被其他程序或用户改变，拒绝覆盖；请重新检查。", "Another program or user changed the current state. Refusing to overwrite it; check again."),
    "unavailable": ("无法可靠复核条件，未执行修改。", "Conditions could not be verified reliably. No change was made."),
    "stale": ("条件已变化或动作已不再适用，未执行修改。", "Conditions changed or the action no longer applies. No change was made."),
    "unsupported": ("此动作没有通过本轮安全门禁，仅提供人工处理入口。", "This action has not passed the safety gate. Use the manual troubleshooting entry instead."),
    "permission": ("权限被拒绝或用户取消提权。", "Permission was denied or elevation cancelled."),
    "dependency": ("依赖失败：{0}", "Dependency failed: {0}"),
    "plan_report": ("## 修复计划与复查记录（已脱敏）", "## Repair Plan and Recheck Record (Redacted)"),
    "recovery_list": ("可恢复的备份：{0}。其余项目无法自动恢复；DNS 缓存会重新生成，服务任务不能完整恢复。", "Recoverable backups: {0}. Other actions cannot be automatically undone; DNS cache rebuilds and interrupted service tasks cannot be fully restored."),
    "restore_confirm": ("恢复可用备份前会检查冲突。DNS 恢复需要单独提权，不覆盖外部改动。继续吗？", "Available backups will be checked for conflicts. DNS recovery needs separate elevation. External changes will not be overwritten. Continue?"),
    "manual": ("高影响或未验证动作：不自动重置网络栈、不结束程序、不取消打印任务、不安装驱动。SFC/DISM 仅在可靠损坏证据和单独确认后才可进入计划；不承诺回滚。", "High-impact or unverified actions: no automatic network-stack reset, process termination, print-job cancellation or driver installation. SFC/DISM require reliable corruption evidence and individual confirmation; recovery is not guaranteed."),
    "network_settings": ("打开网络设置（人工处理）", "Open Network Settings (Manual)"),
    "software_help": ("打开已安装应用设置（人工处理）", "Open Installed Apps (Manual)"),
    "printer_settings": ("打开打印机设置（人工处理）", "Open Printer Settings (Manual)"),
    "network_target": ("目标网址（HTTPS）：", "Target Website (HTTPS):"),
    "network_scope": ("故障范围：", "Problem Scope:"),
    "all_sites": ("所有网站无法访问", "All websites fail"),
    "one_site": ("只有一个网站无法访问", "Only one website fails"),
    "wifi": ("Wi-Fi 已连接但无法上网", "Wi-Fi connected but no internet"),
    "network_title": ("网页打不开 · 分层证据", "Website Access · Layered Evidence"),
    "network_limits": ("仅检查所选目标和两个参照站点；PAC/WPAD、网关 ICMP 限制及单次波动可能影响判断。证书或时间异常不能靠关闭证书验证解决。", "Only the selected target and two reference sites are checked. PAC/WPAD, gateway ICMP restrictions and transient conditions limit conclusions. Certificate or time issues must not be fixed by disabling certificate validation."),
    "target_only": ("参照站点可访问而目标失败，优先核对目标服务、域名、CDN 或特定路径；不是整机断网证据。", "Reference sites respond while the target fails. Check that service, domain, CDN or specific path; this is not evidence of a system-wide outage."),
    "dns_hint": ("多个域名的系统解析失败，DNS 缓存刷新可尝试，但不能保证修复上游 DNS。", "System resolution failed for multiple domains. Flushing DNS cache may help but cannot fix upstream DNS reliably."),
    "proxy_hint": ("直连与代理路径有差异，优先检查代理/PAC 路径；配置存在本身不是故障，不自动清除。", "Direct and proxy paths differ. Check proxy/PAC routing; configuration presence alone is not a fault and will not be cleared automatically."),
    "https_hint": ("DNS 成功但 HTTPS 失败，检查系统时间、证书信任、代理和目标服务；不推断防火墙或证书就是根因。", "DNS resolves but HTTPS fails. Check system time, certificate trust, proxy and target service; no firewall or certificate root cause is assumed."),
    "flush": ("刷新 DNS 缓存", "Flush DNS Cache"),
    "flush_impact": ("只刷新解析缓存，不改变 DNS 服务器；随后分别复查 DNS 与 HTTPS。", "Flush cached lookups without changing DNS servers; DNS and HTTPS are checked separately afterward."),
    "automatic": ("启动应自动运行但已停止的服务：{0}", "Start an Automatic Service That Is Stopped: {0}"),
    "service_impact": ("不修改启动类型；依赖须已运行。服务可能启动任务，不保证解决原始故障。", "Do not change startup type; dependencies must already run. The service may start tasks, and resolution of the original problem is not guaranteed."),
    "service_title": ("服务适用性与依赖", "Service Applicability and Dependencies"),
    "cache_title": ("白名单缓存预览", "Allowlisted Cache Preview"),
    "cache_action": ("隔离缓存：{0}", "Quarantine Cache: {0}"),
    "cache_impact": ("先确认相关程序已关闭；仅隔离明确缓存目录，保留恢复副本，不删除账户资料。相同磁盘保留副本不会释放空间。", "Confirm the related app is closed. Quarantine only the exact cache directory with a recovery copy, excluding account data. Keeping a copy on the same disk does not free space."),
    "cache_closed": ("请先关闭相关程序，或缓存路径存在链接/越界。", "Close the related app first; cache paths must not contain links or escape the allowlist."),
    "cache_done": ("缓存已移入恢复区，原目录可由程序重新创建。", "Cache moved to recovery storage; the app can recreate the original directory."),
    "cache_restored": ("缓存已恢复；没有覆盖后来生成的文件。", "Cache restored without overwriting files created later."),
    "performance_title": ("电脑卡顿 · 连续资源采样", "Slow Computer · Continuous Resource Samples"),
    "sustained": ("采样 {0} 次；持续高占用：CPU {1}，内存 {2}，磁盘 {3}。磁盘活动不可读时保留未知。", "{0} samples; sustained pressure: CPU {1}, memory {2}, disk {3}. Unavailable disk activity remains unknown."),
    "performance_limit": ("持续占用只是线索，不是故障原因。结合系统盘空间、启动项、内存可用量和复现时间；不要因一次峰值结束程序。", "Sustained use is a clue, not a root cause. Compare system-drive space, startup entries, available memory and reproduction time; do not terminate an app because of one spike."),
    "structured_crash": ("崩溃事件的结构化字段（应用路径、版本、异常码、故障模块）", "Structured Crash Fields (App Path, Version, Exception Code, Fault Module)"),
    "yes": ("是", "Yes"), "no": ("否", "No"),
    "full": ("有恢复副本；冲突时不覆盖", "Recovery copy available; conflicts are not overwritten"),
    "best": ("仅能尽力恢复原状态，不能恢复中断任务", "Best effort for previous state; interrupted tasks cannot be recovered"),
    "never": ("不可可靠回滚", "Cannot reliably undo"),
}


def tr(key: str, *values) -> str:
    message = COPY[key][1 if LANGUAGE == "en" else 0]
    return message.format(*values) if values else message
